### ISSUE TITLE
Energie produite PV

### ISSUE THREAD

**Issue by BrunoSpy** [fairecasoimeme/Zlinky_TIC#101]
Bonjour,
Quel est le champ qui permet de relever l'énergie produite par les panneaux solaires en autoconsommation.
Si je comprends bien EAIT permet de connaitre l'énergie injectée sur le réseau (le surplus non consommé) mais je souhaiterais relever la partie autoconsommée.
Merci d'avance

**Comment by fairecasoimeme** [comment]
Bonjour,
je ne suis pas expert dans les systèmes d'autoconsommation mais vous pouvez retrouver toutes les étiquettes en rapport avec la production ici (colonne comment): https://github.com/fairecasoimeme/Zlinky_TIC#mode-standard

**Comment by BrunoSpy** [comment]
Merci
J'ai donc ma réponse : on ne peut avoir que la puissance et énergie injectée dans le réseau, pas la production elle-même. Ce qui est fort logique au demeurant.
