### ISSUE TITLE
Ne recoit plus grand chose d'actuel

### ISSUE THREAD

**Issue by gromo69** [fairecasoimeme/Zlinky_TIC#104]
Hello
Depuis les mises a jour OTA 0006-0007-0008-0009 je ne reçois plus grand chose à jour comme valeur ! 
En effet seul TIC_current_date semble updater toutes les minutes
Dans les logs Zigbee2MQTT je vois cela toute les 60sec. : "zlinky config: standard, three_phase, true, ENGIE ELEC WE"
zha core 2022.9.1 Z2M 1.28.0-1 

restart zha ou Z2M n'y change rien, idem pour reconfigurer le LiXee...

Je ne sais pas comment revenir en arrière OTA sur le firmware 0005 par exemple

Merci de votre aide

Thierry

**Comment by fairecasoimeme** [comment]
Bonjour,
Pour tester si le ZLinky répond, vous pouvez aller dans l'onglet console dev et faire une requête manuelle : 
![image](https://user-images.githubusercontent.com/22256438/193632992-1bd6cdb7-06dd-442c-9139-27b422cd9c38.png)
Certains utilisateurs ont ce type de problème mais je ne sais pas d'où cela provient

**Comment by antoinelibert** [comment]
Bonjour,

Après une mise à jour, il faut penser à le reset : supprimer de Z2M en forçant le unpair, reset le zlinky (10 secs sur le bouton) puis pair de nouveau . J'ai rarement eu un comportement normal sans faire un reset après une màj.

**Comment by gromo69** [comment]
OK merci à tous... en effet supprimé, resetté, ré-appairé puis renommé.. c'est bon j'ai un update complet des valeurs... :-)
