### ISSUE TITLE
ZLinky not working / no report attributes

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#111]
Because I detected that the ZLinky was sending its repoort to a router and not the coordinator 0x0000, I decided to redo the bind. And systématically as I already mentioned here the bind restult in Table full message, and when trying to unbind the response is entry do not exist

See the unbind command screenshot
<img width="881" alt="Screenshot 2022-10-09 at 17 02 00" src="https://user-images.githubusercontent.com/8291674/194764121-84d4f17e-a11d-4cbc-93dd-076b4d981b9d.png">
<img width="760" alt="Screenshot 2022-10-09 at 17 02 14" src="https://user-images.githubusercontent.com/8291674/194764123-de104c5f-ca92-44fc-828e-4237cc0c7f77.png">

And then  the bind command

<img width="910" alt="Screenshot 2022-10-09 at 17 03 02" src="https://user-images.githubusercontent.com/8291674/194764157-b132721b-c5b4-4a2a-b334-1278c221804b.png">
<img width="715" alt="Screenshot 2022-10-09 at 17 03 23" src="https://user-images.githubusercontent.com/8291674/194764160-443a5bb6-79e9-4363-9f4b-ac9ddd4bc1e9.png">

**Comment by pipiche38** [comment]
Here is a frame where the ZLinky 0xef8c sending apparent power to a Router !!!
<img width="715" alt="Screenshot 2022-10-09 at 17 08 24" src="https://user-images.githubusercontent.com/8291674/194764399-92e6af4b-6ca7-40f5-8209-c66611dc2556.png">

**Comment by fairecasoimeme** [comment]
This function has been tested and re tested and re re tested and it's work perfectly.
As you can see in your trace, you tried to unbind an unknow bind.

As I can see with the report to a router, I think you binded (and config reported) with a router and you tried to unbind with the coordinator mac. (which doesn't exist)

As I already said in https://github.com/fairecasoimeme/Zlinky_TIC/issues/93#issuecomment-1243816164 you can verify with debug console. plug your usb TTL module to the Zlinky and use putty with 115200baud. When you reset (reboot) you can get report table and bind table

here is an ZLinky bind table example : 
![Bind_complet](https://user-images.githubusercontent.com/22256438/194811630-b6e0288d-dc3c-4783-93d7-3b9abb214b34.JPG)

**Comment by pipiche38** [comment]
Your function tested and re-tested and work perfectly but in your lab .
As your assumption, you are totaly wrong because the reporting works and suddenly stop working, and it is just by putting the sniffer I was able to see the ZLinky sending reports to a router .

It is up to you to give this level of support and do no trust people reporting issues.

**Comment by fairecasoimeme** [comment]
Copy here your debug console ...

In your side, trust the function which is well-tested and don't draw any quickly conclusions.

**Comment by pipiche38** [comment]
here is the binding tables which show the correct bindings between the ZLinky and the coordinator
<img width="1430" alt="Screenshot 2022-10-12 at 09 13 26" src="https://user-images.githubusercontent.com/8291674/195274891-dde18832-2c40-499d-8973-d1015a10df9a.png">

**Comment by fairecasoimeme** [comment]
This is not that I asked ....
I repeat : plug your usb TTL module to the Zlinky and use putty with 115200 bauds. Push the ZLinky reset button (reboot) and copy/paste the report and bind table.

**Comment by pipiche38** [comment]
at least what I'm showing is the binding exists in the bidding table, and the unbind/bin function doesn't work.
I do not have access to the ZLinky, so I cannot do more
