### ISSUE TITLE
Connectivité extrement difficile

### ISSUE THREAD

**Issue by Zigbee66** [fairecasoimeme/Zlinky_TIC#113]
Bonjour,
Mon coffret avec le compteur Linky se trouve à l'extérieur, en limite de propriété.
Impossible de connecter en direct.
J'ai installé à l'extérieur à une 15 de mts du compteur des ampoules Zigbee (Ikea) qui connectent sans problèmes au réseau, mais impossible de communiquer avec le Lixee. 
Je sais qu'il y a une version avec antenne externe. Est-il possible de la rajouter?
Des conseils pour avoir une liaison stable et fiable?

Merci d'avance:

Eric

**Comment by fairecasoimeme** [comment]
Bonjour,
Non la version avec antenne externe a un autre module dédié. Il faut faire un échange avec le bon matériel.
Contactez-moi par mail contact[at]lixee.fr
