### ISSUE TITLE
PAPP et IINST ne remontent plus depuis MAJ 5.0 -> 9.0 no_route

### ISSUE THREAD

**Issue by bemble** [fairecasoimeme/Zlinky_TIC#114]
Bonjour,

J'avais des soucis de zLinky surchargé, du coup je suis passé sur la version 0.9 no_route du firmware. Cependant depuis cette migration, les valeurs de PAPP et IINST ne remontent plus :
![Capture d’écran 2022-10-18 à 14 13 15](https://user-images.githubusercontent.com/397503/196426229-17ba5bda-7bc0-4682-96a5-538d1d2872a4.png)

Sur les graphs c'est vonstant car c'est la dernière donnée envoyée qui est utilisée, je n'en ai pas reçu depuis la MAJ 0.9 no_route. J'ai rehardé sur mon compteur, le PAPP est bien rempli. J'essaie de rollback sur d'autres versions du firmware (0.9 standard voir 0.5), mais échoue à chaque fois.

A noter que j'ai également ceci qui remonte dans mes logs zigbee2mqtt :
```
Zigbee2MQTT:error 2022-10-18 14:06:01: Failed to configure 'ZLinky', attempt 2 (Error: Bind 0x00158d0005d2a16e/1 seMetering from '0x00212effff073f6f/1' failed (waiting for response TIMEOUT)
    at DeconzAdapter.bind (/app/node_modules/zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts:768:19)
    at Endpoint.bind (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:567:13)
    at Object.bind (/app/node_modules/zigbee-herdsman-converters/lib/reporting.js:40:9)
    at Object.configure (/app/dist/util/externally-loaded.js:605:9)
    at Configure.configure (/app/lib/extension/configure.ts:115:13))
```

Une idée ?

**Comment by fairecasoimeme** [comment]
Bonjour,
le message d'erreur correspond à un problème de portée. (Timeout sur la réponse)
Avez-vous essayé de faire sortir le ZLinky du réseau puis réappairer ?

**Comment by pipiche38** [comment]
https://github.com/fairecasoimeme/Zlinky_TIC/issues/65#issuecomment-1267362376

**Comment by bemble** [comment]
Curieux, parce que d'autres données remontent pourtant :
<img width="1222" alt="Capture d’écran 2022-10-19 à 18 23 55" src="https://user-images.githubusercontent.com/397503/196749158-d5b6ff51-0c66-46e2-9ff9-1dc0cf6dc1a0.png">


Enfin, j'ai essayé de sortir de zlinky du réseau et réappairer, mais impossible, je pense avoir un problème avec mon zlinky, j'ai peur de l'avoir brické en tentant de remettre le firmware v5 :
<img width="782" alt="Capture d’écran 2022-10-20 à 11 00 51" src="https://user-images.githubusercontent.com/397503/196905737-8a770c95-972c-4ce2-b649-800b06758f8b.png">

**Comment by bemble** [comment]
Après reflashage complet via usb avec reset mémoire , tout est rentré dans l’ordre.
