### ISSUE TITLE
Reconstruction du réseau

### ISSUE THREAD

**Issue by bemble** [fairecasoimeme/Zlinky_TIC#129]
Bonjour,

J'ai l'impression que mon Zlinky souffre des même soucis que les devices Xioami/Aqara : il reste connecté au premier device sur lequel il est connecté et si celui-ci est offline, il ne cherche pas d'autre point pour se connecter. Et dans mon cas c'est dommage, il s'est connecté à des ampoules Hue qui ne sont pas constamment allumées (dommage, il y a juste à côté de lui des modules pour mes volets, mais non, il a choisi de passer par ces lumières).

Voilà un partie du schéma de mon réseau :
![signal-2022-11-09-224307_002](https://user-images.githubusercontent.com/397503/201037116-f251c4e5-7e5f-439f-862c-01ebaabbd0ff.jpeg)

 Et ce matin, sans surprise :
<img width="1564" alt="Capture d’écran 2022-11-10 à 09 19 32" src="https://user-images.githubusercontent.com/397503/201038293-017f96ae-966b-4d64-85c8-42a5d5084edc.png">
<img width="1560" alt="Capture d’écran 2022-11-10 à 09 19 22" src="https://user-images.githubusercontent.com/397503/201038314-dbad0170-58d3-4254-b4de-b1fd3b1b53b5.png">

Une idée ? Est-ce un bug ou moi qui ait mal configuré quelque chose ?

Firmware : v10 limited
Clé Zigbee : Conbee II
Soft : Zigbee2mqtt

**Comment by fairecasoimeme** [comment]
Je pense qu'il est d'abord important de ne pas avoir des appareils Zigbee qui ne sont pas constamment alimentés car cela va provoquer une instabilité de votre réseau zigbee. Ensuite, c'est le réseau zigbee qui choisit quel est le meilleur parent d'un appareil selon des critères qui ne sont pas accessibles (couches basses zigbee). 
Quand le ZLinky perd le lien avec le coordinateur, il fait une demande "broadcast" pour trouver un nouveau chemin (s'il existe ou s'il y arrive). Je pense donc que vous avez un souci avec votre réseau zigbee que vous devez régler

**Comment by bemble** [comment]
Merci de votre réponse. Pour l'instant j'ai gardé les ampoules constamment alimentées, avant de changer de manière de faire.
