### ISSUE TITLE
Cluster 0x0004 and 0x0005 reported

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#13]
Is there any particular reason why Group and Scene clusters are available ? ( At least they are reported via a EndPoint descriptor request )

**Comment by fairecasoimeme** [comment]
No reason, I will filter and cancel this cluster

**Comment by pipiche38** [comment]
Still reported on lateste firmware

**Comment by fairecasoimeme** [comment]
Not on the new firmware in release section

Type: 0x8043 (Simple Descriptor Response)
  SQN: 0x88
  Status: 0x00
  Short Address: 0x0F7E
  Length: 22
  EndPoint: 0x01
  Profile ID: 0x0104 (ZigBee HA)
  Device ID: 0x0053 (Unknown)
  Input Cluster Count: 6
    Cluster 0:  Cluster ID: 0x0000 (General: Basic)
    Cluster 1:  Cluster ID: 0x0003 (General: Identify)
    Cluster 2:  Cluster ID: 0x0702 (Smart Energy: Metering)
    Cluster 3:  Cluster ID: 0x0B04 (Unknown)
    Cluster 4:  Cluster ID: 0x0B01 (Unknown)
    Cluster 5:  Cluster ID: 0xFF66 (Unknown)
  Output Cluster Count: 1
    Cluster 0:  Cluster ID: 0x0019 (General: OTA)
