### ISSUE TITLE
Récupération CCASN retourne -32768

### ISSUE THREAD

**Issue by HermesHonshappo** [fairecasoimeme/Zlinky_TIC#133]
Bonjour

Je cherche à comprendre pourquoi, aussi bien sur ZHA que Z2M, le Lixee ne remonte pas le champ CCASN (active power) correctement? Chaque fois, il lit la valeur -32768

Exemple sur Z2M, avec la dernière version du firmware:

<img width="1034" alt="Screenshot 2022-11-14 at 13 01 34" src="https://user-images.githubusercontent.com/97752752/201655264-24cf44a1-771f-4b55-b238-1c3ce7c2980d.png">

**Comment by chryss44** [comment]
Si j'ai tout bien compris, tu es paramètre en Standard pour ton tic et ton compteur est en historique, j'ai ce problème aussi de 32768.

**Comment by chryss44** [comment]
Non non, je pense pas que ce soit bancal mais j'ai le même symptôme que toi sauf qu'il semble que ce soit ce que j'ai décrit le problème....me suis dit bêtement que c'était pareil pour toii.
t'as essayer en inversant le paramétrage côté Zinky en mode standard pour voir si tu as le même résultat ?

**Comment by fairecasoimeme** [comment]
Attention le mode du Linky (historique ou standard) n'est pas paramétrable au travers du ZLinky. C'est Enedis qui paramètre le Linky selon l'ancienneté ou la demande de l'habitant.

Avant de faire le paramétrage sur Z2M, il faut d'abord savoir dans quel mode est votre Linky. (en faisant défilé sur l'écran du Linky par exemple)

Si vous êtes en mode historique, l'information CCASN n'existe pas. Ce qui explique la valeur par défaut. pour connaitre les étiquettes valident, il faut consulter le [README
](https://github.com/fairecasoimeme/Zlinky_TIC#mode-historique)

**Comment by chryss44** [comment]
Je viens de faire la demande en passant par Ennemis et ca ne pose aucun problème, il faut juste demander à basculer le TIC d'historique à Standard. La personne a qui tu vas faire la demande remplie un formulaire et il y a un batch qui bascule ton compteur à minuit en mode souhaité.

**Comment by HermesHonshappo** [comment]
Tu as eu plus de bol que moi. La personne que j'ai eu chez Enedis n'a rien voulu faire si ça ne passait pas par mon fournsseur d'énergie avant.
Peu-être que ça dépend des accords entre Enedis et le fournisseur.

**Comment by HermesHonshappo** [comment]
Je confirme qu'une fois le Linky basculé en mode standard, on récupère bien le CCASN

<img width="446" alt="Screenshot 2022-11-17 at 12 22 24" src="https://user-images.githubusercontent.com/97752752/202433728-b301dda4-192c-4998-9266-d446a9734d53.png">

**Comment by BRSS73** [comment]
![image](https://user-images.githubusercontent.com/15141208/202843209-e9badfab-82c8-443f-919e-feb28cf09fe5.png)

Pas toujours malheureusement

**Comment by HermesHonshappo** [comment]
Etrange. Si tu vas sur ton compteur Linky, et tu appuie sur la flèche vers le bas jusqu'à ce qu'il affiche TIC, il dit quoi? Historique ou Standard?

**Comment by BRSS73** [comment]
Mon compteur est en mode Standard et mon Zlinky est forcé sur les paramètres (standard, single_phase, false, etc.) pour limiter les erreurs d'interprétation.

Je ne suis globalement pas satisfait du Zlinky. J'ai de fréquentes déconnexions, il produit un gros bavardage sur le réseau (firmware v11 "limited") en envoyant 5-6 messages en rafale avec juste DATE qui change et de temps en temps, il flood mon coordinateur au point que je suis obligé de le retirer de force du réseau et de refaire l'appairage.

Aujourd'hui, je tente le Debounce sur Z2M pour réduire le flood sur MQTT.

**Comment by fairecasoimeme** [comment]
> J'ai de fréquentes déconnexions, il produit un gros bavardage sur le réseau (firmware v11 "limited") en envoyant 5-6 messages en rafale avec juste DATE qui change et de temps en temps, il flood mon coordinateur au point que je suis obligé de le retirer de force du réseau et de refaire l'appairage.

ça n'a rien à  voir avec le zlinky. C'est selon comment votre plugin est paramétré. Si vous "poll" le Zlinky réduisez le polling, si vous avez créé des rapports, vérifiez les paramètres de vos rapports pour ne pas flood...

**Comment by BRSS73** [comment]
Poll à -1.
Le reporting avec les valeurs par défaut.

**Comment by fairecasoimeme** [comment]
Le ZLinky n'envoie rien de lui même. S'il envoie 6 messages DATE en rafale, c'est qu'on lui a demandé

**Comment by BRSS73** [comment]
Alors je vais revoir encore une fois le paramétrage dans Z2M.
