### ISSUE TITLE
Cluster Power Configuration ajouté en v12.0 non déclaré ?

### ISSUE THREAD

**Issue by pdecat** [fairecasoimeme/Zlinky_TIC#140]
Bonjour @fairecasoimeme,

j'ai ouvert une PR https://github.com/zigpy/zha-device-handlers/pull/1962 pour ajouter le support du nouveau cluster Power Configuration ajouté en v12.0 dans Home Assistant / ZHA.

Et j'ai été surpris de constater que ce cluster n'est apparemment pas déclaré par le ZLinky_TIC : https://github.com/zigpy/zha-device-handlers/pull/1962/commits/f05d54651776347c28aa480495648c56ee7be2a4

C'est volontaire ?

**Comment by WarC0zes** [comment]
Bonjour  @pdecat,
je viens de faire la maj en v12 limited et je vois bien le cluster dans la gestion du Zlinky.
![zlinky voltage](https://user-images.githubusercontent.com/91471397/203687204-897dd8d8-82ab-43eb-a9a1-4d2673ef2b70.png)

**Comment by fairecasoimeme** [comment]
> Et j'ai été surpris de constater que ce cluster n'est apparemment pas déclaré par le ZLinky_TIC : [zigpy/zha-device-handlers@f05d546](https://github.com/zigpy/zha-device-handlers/commit/f05d54651776347c28aa480495648c56ee7be2a4)
> 
> C'est volontaire ?

Non, le cluster est normalement "discoverable"

**Comment by pdecat** [comment]
Hmm, j'ai eu des soucis également lors du passage de v11 à v12 en OTA, et j'ai dû ré-appairer également, mais je n'ai pas supprimé côté ZHA pour ne pas perdre l'historique. C'est peut-être à de ça.

**Comment by pdecat** [comment]
> Bonjour @pdecat, je viens de faire la maj en v12 limited et je vois bien le cluster dans la gestion du Zlinky. ![zlinky voltage](https://user-images.githubusercontent.com/91471397/203687204-897dd8d8-82ab-43eb-a9a1-4d2673ef2b70.png)
> 
> Par contre j'ai supprimer le Zlinky et je les réappairer après la maj en v12.

Du coup, le quirk qui permet de requéter le cluster _manufacturer specific_ ne s'applique plus à ton ZLinky semble-t-il.

**Comment by WarC0zes** [comment]
@pdecat  c'est exacte j'avais même pas remarquer, sa utilise plus le quirk.
![Screenshot_20221124_104817](https://user-images.githubusercontent.com/91471397/203752252-7a0ffd87-e15d-4ef1-901d-0845092be4b1.jpg)

**Comment by pdecat** [comment]
Oui, car la signature change dans ton cas mais pas le mien 🤔

**Comment by pdecat** [comment]
C'est bien un problème de cache côté ZHA.

**Comment by pdecat** [comment]
@WarC0zes tu peux aussi voir si le quirk s'applique directement sur le device :

![image](https://user-images.githubusercontent.com/318490/203781644-a10b70af-6e5d-4604-a28b-76c8676dbfd1.png)

**Comment by WarC0zes** [comment]
@pdecat
je savais mais comme sa utilise plus de quirk, je voulais te montrer mon tableau flex ou on voit les quirks utiliser ou pas.
![zlinky zigpy](https://user-images.githubusercontent.com/91471397/203797667-58cf810e-d6e8-472c-89c6-87563d47f0bb.png)
