### ISSUE TITLE
Ne fonctionne plus en V12

### ISSUE THREAD

**Issue by mducommun** [fairecasoimeme/Zlinky_TIC#141]
Bonsoir,
Depuis mon passage en V12, mon module ne voit plus aucun changement de valeurs coté linky...
Il est resté bloqué avec le même index de base et une conso PAPP de 510VA.

Je l'ai débranché/rebranché, reboot de HomeAssistant, reboot de ma zigstar rien n'y fait.

Je voulais procéder a un downgrade mais malgré le tuto, je ne trouve pas le fichier lixee.js.

Avez vous une idée?
Merci d'avance

**Comment by mathieu-mp** [comment]
Bonjour @mducommun,

Je rencontre le même problème, comment l'as-tu résolu ?

Merci !

**Comment by mducommun** [comment]
Bonsoir,
Il a fallu que je supprime le zlinky de z2m puis que je fasse l’appairage de nouveau et il a re fonctionner.

**Comment by mathieu-mp** [comment]
Merci pour ce retour
