### ISSUE TITLE
Requesting Binding Table respond with "Reserved" status

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#15]
When requesting the Binding Table, we get a status code of 0xc1 "Reserved" and we don't get the Binding table !

**Comment by fairecasoimeme** [comment]
How you request Binding table please ? with which command ? it's possible that is not implemented

**Comment by pipiche38** [comment]
Using Cluster 0x0033 with Raw APS command ( 0x0530)

**Comment by fairecasoimeme** [comment]
OK, I'll see

**Comment by fairecasoimeme** [comment]
What is the goal to get Binding table for ZLinky ? Could you explain a usecase for binding Zlinky to an other device ?

**Comment by pipiche38** [comment]
The purpose is simply to get the binding table of any Zigbee devices, by queering them.
For debugging purposes for example, it is interesting to see what is in the binding table of a device, to see if the binds are correct or not.
