### ISSUE TITLE
Presque pas de métriques 

### ISSUE THREAD

**Issue by kimizz59** [fairecasoimeme/Zlinky_TIC#153]
Bonjour,

J'ai connecté un ZLinky_TIC à mon HA via Z2M mais je n'ai jamais réussi à avoir des informations intéressantes. 

Version du firmware : 4000-0012
Zigbee2MQTT version: 1.28.4-1 
Mode linky : Standard (j'étais en histo et suis passé en standard en espérant un changement, hélas non)

J'ai uniquement ce genre d'info
![image](https://user-images.githubusercontent.com/61160797/208198446-a0c373f8-55db-4f3c-bd50-3f6c5ebe463a.png)
![image](https://user-images.githubusercontent.com/61160797/208198492-cdb4419e-9713-406e-826d-3f7034e245d0.png)

Je n'ai que ce genre de log actuellement : 
`Zigbee2MQTT:info  2022-12-16 23:18:39: MQTT publish: topic 'zigbee2mqtt/Lixee', payload '{"active_enerfy_out_d01":0,"active_power":-32768,"active_power_max":-32768,"active_power_ph_b":-32768,"active_register_tier_delivered":"","apparent_power":65535,"available_power":null,"average_rms_voltage_meas_period":0,"current_date":"","current_index_tarif":0,"current_price":"","current_summ_delivered":0,"current_tarif":"BASE","current_tier1_summ_delivered":0,"current_tier2_summ_delivered":0,"drawn_v_a_max_n1":0,"linkquality":164,"message1":"","message2":"","meter_serial_number":"","power_threshold":null,"relais":0,"rms_current":65535,"rms_current_max":65535,"rms_voltage":65535,"site_id":"","software_revision":null,"status_register":"","update":{"installed_version":"4000-0012","state":null},"update_available":null,"warn_d_p_s":0}'`

J'ai tenté de passer les paramètres spécifique en manuels, j'ai tenté de delete le lixee pour le réappairé à multiple reprises mais je n'ai jamais plus que ça.

Ma clé Zigbee est à 3m de mon linky, je ne pense pas que cela soit un problème de distance.

Assez nouveau sur HA et Z2M, je ne vois pas trop quoi tester de plus et où je pourrais choper des infos intéressantes pour résoudre mon souci.

**Comment by josephpage** [comment]
Avez-vous essayé de jouer avec les différents paramètres de l'onglet "Paramètres (spécifiques)" dans Zigbee2Mqtt ? Si j'étais dans votre situation c'est ce que je ferais.

Mais c'est vrai que le fait que même le Serial Number ne remonte pas est très mauvais signe.
Si vous ne trouvez pas de solution avec différents réglages et après plusieurs ré-appairage, il vous reste à demander de l'aide au fabricant : https://lixee.fr/nous-contacter

**Comment by kimizz59** [comment]
Yes j'ai essayé un peu de jouer un peu avec les options.
Je ne maitrise pas les métrique "poll" en revanche, avec quelles valeurs je pourrait faire des essais à ce niveau là ?
![image](https://user-images.githubusercontent.com/61160797/208268519-efac13de-eb60-4581-9acc-5973d9ea1996.png)

Si avec ça je n'arrive toujours rien, je vais contacter le fabricant directement dans ce cas.

**Comment by CladStriffe** [comment]
Bonjour,

Deja on voit une bizarrerie : les valeurs dans l'onglet "expose" sont celles du mode historique. 
Essayez dans l'onglet "paramètres spécifiques" de mettre le mode à "standard". 
Puis single phase et false si vous n'avez qu'une phase et pas de production.

**Comment by CladStriffe** [comment]
Les valeurs dans "expose" sont celles du mode historique. 
C'est toujours ça que vous avez même après avoir changé manuellement dans paramètres spécifiques sur "standard" ?

**Comment by kimizz59** [comment]
Yes, ma config est celle sur le screen juste au dessus. J'ai également testé en production "false".
J'ai vérifié, je suis bien en mode standard sur la TIC chez Total, elle était en histo au début, lors de mes premières mises en place.
Je pense qu'un réappairage suffit lors d'un changement de mode de TIC (je ne compte même plus le nombre de réappairages que j'ai fait) mais je vais vérifier s'il n'y a pas de manipulation particulières dans ce genre de cas.

Il est possible qu'au début j'ai vu une maj disponible et l'ai lancé. Après pas mal de recherche je vois que cela pourrait poser des soucis (je ne sais pas si c'est la cause du miens).

Mardi je testerais cette procédure (je n'ai pas un accès physique constant à mon installation)
![image](https://user-images.githubusercontent.com/61160797/208298633-1b36cd87-4576-4c8a-a04d-13e485f0c29b.png)
source : https://www.domo-blog.fr/test-lixee-teleinformation-zigbee-avec-home-assistant-jeedom/

**Comment by r0m1CH** [comment]
Bonjour,
J'ai un souci similaire il me semble.
Je suis passé en standard récemment (y'a un ou deux jours) et depuis je n'ai plus les valeurs "standards"
UMOY1, URMS1... mais j'ai pleins d'autres trucs.

J'ai tenté de réappareiller, de redémarrer Z2M... rien n'y fait.

Je suis en tempo mais je sais pas ce qu'il me manque.

![image](https://user-images.githubusercontent.com/373802/224353149-8625d8de-618e-48ba-b517-73bf40ebcf1f.png)

![image](https://user-images.githubusercontent.com/373802/224353308-8fd9357c-b484-4247-975a-e141026c3f34.png)

Une idée ?

**Comment by r0m1CH** [comment]
Bon je viens de relancer Z2M après avoir forcé les paramètres Standard + 1 phase + pas de production.
J'ai des infos en plus mais pas les bonnes:

![image](https://user-images.githubusercontent.com/373802/224377066-a9a4385f-f213-47f9-a183-f4cc8ed5450c.png)

Je sais vraiment pas ce que je fais de mal.

**Comment by fairecasoimeme** [comment]
Quel est le LQI du ZLinky ?

**Comment by r0m1CH** [comment]
Il oscille entre 127 et 180.

**Comment by fairecasoimeme** [comment]
Pouvez-vous générer un schéma réseau et partager ?

**Comment by r0m1CH** [comment]
C'est un peu brouillon mais ça donne ça:
![image](https://user-images.githubusercontent.com/373802/224727975-0014c26c-8989-4dea-a0ea-7b96e030e6b5.png)

**Comment by r0m1CH** [comment]
Une idée de ce qui me manque ?

**Comment by r0m1CH** [comment]
Bon je crois que j’ai trouvé mon souci.

Mon Linky était repassé en mode historique sans raison particulière (peut être le changement de provider)
Il a fallu donc rebasculer en mode standard puis:

Reconfiguration de la clé Lixee dans Zigbee2Mqtt
Redémarrage de Zigbee2Mqtt
Forcer le mode standard dans la conf Zigbee2Mqtt (le mode auto n’a semble-t-il pas fonctionné)
Redémarrage de Zigbee2Mqtt
Au bout de 4/5 minutes après le rédémarrage j’ai retrouvé mes valeurs habituelles (Tension, intensité…).

Je pense qu’il est possible de reconfigurer la clé + changer le mode standard en une action mais je vous décris ce que j’ai fait si jamais ça peut en aider un.

Bon courage !

**Comment by kimizz59** [comment]
Je vois que cette issue est toujours open
De mon côté j'avais fait les MAJ OTA (je ne sais pas si c'est lié)
J'ai fait des tests avec le propriétaire du dongle, celui-ci a été changé et cela fonctionne maintenant correctement.
Je ne lance plus les MAJ OTA depuis, je ne sais pas si c'était lié
