### ISSUE TITLE
Non remontée index BBRHPJR

### ISSUE THREAD

**Issue by githubegins** [fairecasoimeme/Zlinky_TIC#159]
Vous pouvez supprimer cette issue.
Je dois clarifier mon problème... ma description est incohérante.

**Comment by Phil2222** [comment]
Bonjour, 
J'ai de mon côté depuis une restauration de sauvegarde jeedom en fin de journée une non remontée de l'index BBRHCJR.
Comme ça me parait très proche de ce constat, je me permets de rebondir. 
Avez-vous trouvé votre solution ? 
De mon côté, tous les index remontent parfaitement sur mon lixee (qui est a priori en v5) mais impossible de remonter le BBRHCJR... 
JE n'ai pas en mémoire l'apparition de cette erreur avant la restauration jeedom, mais comme il n'y a que cet index qui ne remonte pas, je me demande si je ne loupe pas une astuce...
Le lixee communique avec une clé conbee2 connectée sur une freebox delta avec jeedom et le plugin zigbee... Jusqu'ici tout fonctionnait plutôt bien...

Merci d'avance de vos pistes...

**Comment by Phil2222** [comment]
Bon et bien en creusant dans le détail du point dans jeedom, l'info brute remontait bien mais n'apparaissait pas dans jeedom. Une ébauche de solution a été de recréer une commande avec la même logical ID que l'index qui n'apparaissait plus et tout est revenu comme par magie...
Sujet clos de mon côté...

**Comment by githubegins** [comment]
Effectivement. Le fait d'avoir recréer un nouvelle commande avec la même logic_id semble résoudre le problème.
A noter que ce n'est pas la nouvelle commande qui se met correctement à jour. Mais c'est bien l'ancienne commande qui s'actualise alors qu'elle ne s'actualisait plus.
