### ISSUE TITLE
Zlinky clignote sans arrêter.

### ISSUE THREAD

**Issue by VianneyHENON** [fairecasoimeme/Zlinky_TIC#164]
Bonjour,

J'ai reçu aujourd'hui mon Zlinky.
A peine branché, il se met à clignoter sans arrêter:

J'appuie sur le bouton reset pendant 10s et rebelotte il clignote sans arrêt.

https://user-images.githubusercontent.com/122823766/212747082-e247b918-899e-4b4b-9485-a1cb80010e8d.mp4

Merci pour votre aide.

En parallèle, j'ai envoyé ce message à l'adresse email contact[at]lixee.fr avec les références de la commande.

**Comment by fairecasoimeme** [comment]
Bonjour,

Quand le ZLinky clignote sans s'arrêter, c'est qu'il n'arrive pas être appairé souvent dû à un problème de portée.
