### ISSUE TITLE
Problème d'unité de mesure pour le tarif dans home assistant

### ISSUE THREAD

**Issue by Nemesis24** [fairecasoimeme/Zlinky_TIC#169]
Voici le message retourné:
![image](https://user-images.githubusercontent.com/25956796/214274154-b8695c9e-9df1-4736-9bb5-7d28f3d1f5f8.png)

**Comment by fairecasoimeme** [comment]
Bonjour,
votre problème n'a pas de lien avec le firmware du ZLinky. Vous devriez aller voir sur les réseaux de home assistant.
Fred

**Comment by Nemesis24** [comment]
Bonjour, merci pour votre réponse.
