### ISSUE TITLE
Option Tempo

### ISSUE THREAD

**Issue by mducommun** [fairecasoimeme/Zlinky_TIC#171]
Bonjour,

Est il envisageable d'ajouter l'option tempo au Zlinky ? Quid des tarifs ?

Merci d'avance
Bonne journée

**Comment by fairecasoimeme** [comment]
Bonjour,

Le ZLinky gère déjà l'option tempo (bleu) https://github.com/fairecasoimeme/Zlinky_TIC#subscription-optarif-values

Pour les tarifs, c'est aux plugins/box de le gérer

**Comment by mducommun** [comment]
Autan pour moi.. désolé :)
