### ISSUE TITLE
Papp does not update after ha2023.2.1

### ISSUE THREAD

**Issue by Geoffrey54** [fairecasoimeme/Zlinky_TIC#172]
La puissance apparente ne se met plus a jour avec la dernière version de HA2023.02.01 et z2mqtt 1.30.0-1.

après plusieurs redemarrage de ha et z2mqtt pas de mise a jour. Le module est dans la dernière version également (12)

merci

**Comment by fairecasoimeme** [comment]
Il faut je pense vérifier les logs car là, impossible de déduire quoi que ce soit

**Comment by WarC0zes** [comment]
la puissance apparente fonctionne chez moi en Z2M 1.30.1 et core 2023.2.2
![zlinky z2m 1 3 0 1](https://user-images.githubusercontent.com/91471397/217280276-9907626b-b1b3-4785-867e-2e939f910a55.png)

**Comment by Geoffrey54** [comment]
J’ai supprimé le device sans forcer, ensuite reppairer et redémarrer z2m et c’est ok. On peit clore
