### ISSUE TITLE
Lixee sature t-il mon réseau zigbee ?

### ISSUE THREAD

**Issue by Patoche781** [fairecasoimeme/Zlinky_TIC#195]
Bonjour.
Depuis 2 jours mon réseau zigbee est devenu très lent au point que mes commandes de prises secteur Noos dysfonctionnent.
Auparavant tout fonctionnait parfaitement.

Je soupçonne qu'EDF à changé son mode (Base->Histo) et donc à Zlinky_Tic d'envoyer trops de requêtes sur le réseau zigbee au point de tout faire ralentir par saturation.

Actuellement mon compteur Linky indique être en mode "Tic historique" avec un contrat pris chez EDF avec un abonnement type:
 "Vert electrique Week-end" cet à dire HP + HC (Midi + Nuit + WE).

J'ai donc paramétré mon Zlinky_Tic (Vers firmware 4000-0013 du 20230214 et LQI=96)en mode "Historique" + Single _phase avec le menu "Historique-HCHP"
Les autres menus "Historiques" ne donnent pas plus d'amélioration.

Dans HA (à jour) seul le sensor.lixee_hchc_2 me donne ce qui correspond à "Index Mid" affiché sur le compteur Linky.

HCHC exposé dans Z2M est: 16034.339 kW
HCPC exposé dans Z2M est: 0 kW
OPTARIF exposé dans Z2M est: "Base" -> ???
PTEC exposé dans Z2M est: "TH.."
HHPHC exposé dans Z2M est: "0" 

Lorsque j'arrête mon Z2M puis Mosquito et les redémarre, des logs de Z2M suivants s'affichent très nombreux:
zlinky config: historique, single_phase, false, HC..
Zigbee2MQTT:info  2023-05-10 11:49:55: MQTT publish: topic 'zigbee2mqtt/Lixee', payload '{"active_register_tier_delivered":"TH..","apparent_power":420,"available_power":45,"current_summ_delivered":16034.57,
"current_tarif":"BASE","current_tier1_summ_delivered":16034.57,"current_tier2_summ_delivered":0,"linkquality":93,"meter_serial_number":"xxxxxxxx","rms_current":2,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
Zigbee2MQTT:info  2023-05-10 11:49:58: MQTT publish: topic 'zigbee2mqtt/Lixee', payload '{"active_register_tier_delivered":"TH..","apparent_power":410,"available_power":45,"current_summ_delivered":16034.57,
"current_tarif":"BASE","current_tier1_summ_delivered":16034.57,"current_tier2_summ_delivered":0,"linkquality":96,"meter_serial_number":"xxxxxxxx","rms_current":2,"rms_current_max":90,"schedule_h_p_h_c":0,"update":{"installed_version":13,"latest_version":13,"state":"idle"},"update_available":null,"warn_d_p_s":0}'
------
------
------
Toute commande de prises zigbee Noos est dès lors très ralentie voir aléatoire avec un message de Z2M m'indiquant qu'elles ne sont pas bloquées par list.

Pouvez-vous m'aider et me confirmer si les paramétrages sont les bons.

Merci.

**Comment by Patoche781** [comment]
Merci pour votre réponse quasi immédiate et le temps accordé pour les explications !
j'ai bien positionné mes paramètres sur "Historique / Base" qui me rapportent bien ma consommation globale, ce qui me suffit pour ma part ...
Une dernière précision: quand vous dites "il faut supprimer l'appareil" c'est le Lixee ? Si c'est le cas je ne vais pas m'y essayer car l'appairage est parfois ... compliqué. De plus une éventuelle pertes de données "d'historiques" m'est rédhibitoire et donc je vais plutôt attendre les mises à jours de HA ;-) .
Cordialement.

**Comment by fairecasoimeme** [comment]
Avez-vous juste tenter de redémarrer Z2M ?

**Comment by Patoche781** [comment]
Bien sur et de nombreuses fois. J'ai même redémarré la VM et son hôte: rien de changé...
Par contre ce matin tout est redevenu normal: les commandes de mes prises Noos AZ1 passent normalement, le script d'allumage auto par capteur de présence (le seul que j'ai gardé ) fonctionne parfaitement ... C'est à n'y rien comprendre !
C'est la première fois depuis le 08/2022 que j'ai ce problème et surtout j'en ai pas trouvé la source ...
Le principal est que cela refonctionne sans tout à refaire mais je reste vigilant !
Merci pour m'avoir aidé à la résolution de ce cas ... inexpliqué .
l

**Comment by Gonioul** [comment]
Base vers histo? C'est histo vers std.
Une astuce qui marche sur zwave et probablement sur zigbee est de débrancher le dongle, attendre un peu et le rebrancher.
Par contre si effectivement il y a un changement de mode TIC histo->std, il faut impérativement supprimer le device dans HA et redémarrer Z2M sinon les nouveaux paramètres ne seront pas pris en compte, Z2M n'écrase pas un device existant.

**Comment by Patoche781** [comment]
Bonjour et merci Gonioul !
Je n'aurrai pas à essayer ta manip: tout est redevenu parfaitement opérationnel sans que j'ai eu à toucher à ma configuration matérielle ! Les logs ne m'ont pas permis de lever le doute car je ne sais pas encore les interpréter (pas évident de connaître un protocole au pied levé). Je pense que mes multiples redémarrage tant Z2M que HA et Proxmox ont du solutionner le problème (je pense à un capteur de proximité foireux qui me plantait mes scripts d'allumage auto).
Encore merci à la communauté pour m'avoir proposé des solutions de dépannage !

**Comment by Patoche781** [comment]
Bonjour. Effectivement le problème est résolu sans action de ma part. Le
post peut être fermé. Merci pour le suivi.
Cdt.

Le mar. 6 juin 2023, 13:09, Vincent Legoll ***@***.***> a
écrit :
