### ISSUE TITLE
ZLinky semble non alimenté à certains moments

### ISSUE THREAD

**Issue by VianneyHENON** [fairecasoimeme/Zlinky_TIC#199]
Bonjour,
Après des mois de fonctionnement, dimanche dernier le Zlinky est apparu hors ligne dans HA, je l'ai débranché quelques heures, puis après rebranchement la LED a clignoté de nouveau et donc en ligne dans HA.

Aujourd'hui, le phénomène se reproduit, que faire ? Problème avec le Zlinky ou le Linky?

Merci d'avance.

**Comment by VianneyHENON** [comment]
Bonjour,
La version est 4000-0012, je n'arrive pas a passer en 13 en OTA avec Home Assistant.
Mais je pense que j'ai eu le même souci que uncle-buzz, avec le souci de tension sur les bornes du tic.
https://github.com/fairecasoimeme/Zlinky_TIC/issues/193

![image](https://github.com/fairecasoimeme/Zlinky_TIC/assets/122823766/777f17c8-3bea-4b8b-94e1-75b95c87a760)

**Comment by fairecasoimeme** [comment]
Je remarque qu'en ce moment, il y a plus de cas de coupure de l'alimentation de la téléinformation des Linky que d'habitude. soit des mises à jours ou peut-être lié à la chaleur ... je vais remonter une liste de cas. pouvez-vous m'envoyer le modèle et la marque de votre linky ou une phot par mail ?

**Comment by VianneyHENON** [comment]
Bonjour,
Linky de marque ITRON modèle T10716
Autre référence ITRON ITE411L3B

**Comment by VianneyHENON** [comment]
Bonjour,
Le phénomène est de nouveau réapparu cette nuit.
Pour info.

**Comment by louistrapadoux** [comment]
bonjour, il m'est arrivé aussi la même chose aujourd'hui, le zlinky ne semblait plus allimenté, après l'avoir deinstaller du compteur et attendu quelques heures comme suggeré, il s'est remi a fonctionner. la version du firmware est la dernière : 4000-0013
