### ISSUE TITLE
Would be great to document Model Name and Manufacturer Name

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#2]
It would be great to document also what are the Attributes values of the Basic 0x0000 Cluster as 

0x0000 | ZCLVersion
0x0001 | ApplicationVersion
0x0002 | StackVersion
0x0003 | HWVersion
0x0004 | ManufacturerName
0x0005 | ModelIdentifier
0x0006 | DateCode
0x0007 | PowerSource

**Comment by fairecasoimeme** [comment]
added to README
