### ISSUE TITLE
Cluster 0x0702 , Attribut 0x0000 - Data Type used in not standard

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#20]
Data Type used in 0x23 while it must be 0x25 
![Uploading Screenshot 2021-11-11 at 21.51.52.png…]()

**Comment by pipiche38** [comment]
ZLinky:

`ZiGate-V2: (ZiGate-V2) Decode8100 - idx: 32 Read Attribute Response: [342b:01] ClusterID: 0702 MsgSQN: 74, i_sqn: 40, AttributeID: 0000 Status: 00 Type: 23 Size: 0004 ClusterData: >00000000<`


Un Device autre ( Tuya Plug)
Decode8102 - Receiving a message from unknown device: [c0a1:01] ClusterID: 0702 AttributeID: 0000 Status: 00 Type: 25 Size: 0006 ClusterData: >000000000039<

**Comment by fairecasoimeme** [comment]
Fixed for the future version

**Comment by fairecasoimeme** [comment]
fixed on new v3 release
