### ISSUE TITLE
Condensateur

### ISSUE THREAD

**Issue by adri123** [fairecasoimeme/Zlinky_TIC#205]
Bonjour, je souhaiterai mettre un condensateur pour éviter les problèmes de déconnexion.
J'ai acheté un 100micro farad 6.3 V classique en forme de cylindre.
Puis je le souder ou il faut nécessairement le modèle indiqué ?
Merci.

**Comment by fairecasoimeme** [comment]
Bonjour,
Oui cela peut faire l'affaire.

**Comment by adri123** [comment]
Merci, pouvez m'indiquer où mettre la borne plus du condensateur ?

**Comment by fairecasoimeme** [comment]
Vous avez les infos sur les photos de l'errata du README.
la borne + est là où il y a la bande blanche du condensateur tantale
