### ISSUE TITLE
CORRECTION IN DOCUMENTATION UMOY2 x2

### ISSUE THREAD

**Issue by djsyl** [fairecasoimeme/Zlinky_TIC#21]
UMOY2 | 0xB04 | 0x0911 | RP | Triphasé | Uint16 | 3 car | V | Tension moy. ph. 2 | 0
UMOY2 | 0xB04 | 0x0A11 | RP | Triphasé | Uint16 | 3 car | V | Tension moy. ph. 3

VS

UMOY2 | 0xB04 | 0x0911 | RP | Triphasé | Uint16 | 3 car | V | Tension moy. ph. 2 | 0
UMOY3 | 0xB04 | 0x0A11 | RP | Triphasé | Uint16 | 3 car | V | Tension moy. ph. 3

Have a fun

**Comment by fairecasoimeme** [comment]
Thanks,
Fixed
