### ISSUE TITLE
Question liée aux changement de mode routeur standard ou Limited (OTA)

### ISSUE THREAD

**Issue by expresscisco** [fairecasoimeme/Zlinky_TIC#212]
Bonjour,

Es-il maintenant possible de passer d'un firmware v12 router standard à v13 Limited en OTA via Home Assistant ?

En vous remerciant par avance.

**Comment by fairecasoimeme** [comment]
Bonjour,
Non, En OTA, on ne peut faire la mise à jour que sur les même types de firmware.
Je vous conseille plutôt de faire une mise à jour de la V12 standard vers la v13 standard
