### ISSUE TITLE
Surr Tempo: HCHP n'est pas le total the HP ni est HCHC le total HC, c'est que jours blanc

### ISSUE THREAD

**Issue by vingerha** [fairecasoimeme/Zlinky_TIC#221]
Voir dessus
HCHP/HCHC manquent les données des jours white/red

![image](https://github.com/fairecasoimeme/Zlinky_TIC/assets/44190435/62ed24cf-de6d-408a-a250-ec7ffec0d5be)

**Comment by vingerha** [comment]
La question c'est si HCHP ou HCHC deviennent du Linky ou Lizee ou de l'intégration

**Comment by fairecasoimeme** [comment]
Pour mieux comprendre les étiquettes, il faut lire le [readme](https://github.com/fairecasoimeme/Zlinky_TIC#subscription-optarif-values)

Un couple cluster / attribut peut correspondre à plusieurs abonnement.

Dans votre cas les étiquettes remontée par Z2M : BBRHCJB / HCHC et EJPHN correspondent à la même valeur : 0x0702 | 0x0100
Je pense que vous devez sélectionner votre abonnement dans Z2M pour que ce soit plus clair.

**Comment by vingerha** [comment]
Z2M est sur Standard - Tempo ce qui n'est pas dans la docu
BBRHPJW change HCHP pas...des suggestions bienvenu :)
![image](https://github.com/fairecasoimeme/Zlinky_TIC/assets/44190435/5beaac0c-d29b-4fda-a7c3-7f9f89c0ef4e)

**Comment by fairecasoimeme** [comment]
Normal HCHP n'existe pas sur un abonnement tempo

**Comment by vingerha** [comment]
OK... donc je l'ignore ...c'est bon a savoir, merci
