### ISSUE TITLE
PTEC ne remonte pas

### ISSUE THREAD

**Issue by Titom59** [fairecasoimeme/Zlinky_TIC#23]
Bonjour ayant reçu le module je me suis attelé à l'inclusion de celui sur zigbee2mqtt grâce à [https://gist.github.com/ralmn/02de46e193bf111062f15be07d3e9bd2](https://gist.github.com/ralmn/02de46e193bf111062f15be07d3e9bd2) 

Je suis en mode historique avec les HC et HP mais le module ne mère monte pas l'info.

**Comment by d3v2a** [comment]
C'est normal, car cet élément n'a d'attribut dans le fichier, il faut remplacer la ligne 49 par
```js
{"name":"PTEC","unit":"-","clusterId":1794,"attributId":32,"comment":"","description":"Periode tarifaire en cours","cluster":"seMetering","attribut": 32,"triphase":false,"production":false,"standard":false},
```

**Comment by ralmn** [comment]
L'attribut en 32 (`0x20`) n'est pas connu dans la lib de Z2M. 

Par contre @fairecasoimeme  je le ne vois pas non plus dans la spec https://zigbeealliance.org/wp-content/uploads/2021/10/07-5123-08-Zigbee-Cluster-Library.pdf (page 715)...

**Comment by fairecasoimeme** [comment]
Salut,
si dans la doc, il y a bien l'attribut 0x20 - ActiveRegisterTier Delivered (page 716)
![image](https://user-images.githubusercontent.com/22256438/142015863-8725dbe0-b7a7-42bf-9e0e-b2074e38fb87.png)

**Comment by fairecasoimeme** [comment]
Pour le PTEC, l'info existe bien côté ZLinky, il remonte bien un CString (data type 0x42) avec 4 caractères : HP.. ou HC..

**Comment by ralmn** [comment]
Effectivement j'avais mal vu dans la spec

**Comment by newbeetle** [comment]
Sous Jeedom la requête "clusterId":1794,"attributId":32 ne renvoie aucune information

**Comment by newbeetle** [comment]
Finalement au bout d'un certain temps, la remontée se fait
