### ISSUE TITLE
Compatibilité ZLinky_TIC avec Linky Landis Gyr+

### ISSUE THREAD

**Issue by PCluzz** [fairecasoimeme/Zlinky_TIC#231]
Bonjour, avant d'acheter un ZLinky_TIC, je voudrais m’assurer que mon compteur Linky est compatible. 
![Linky](https://github.com/fairecasoimeme/Zlinky_TIC/assets/63190536/a4159b1b-a2de-4e0b-94e4-18c0bf8098a7)
C'est un Landis Gyr+ L2065 G3. les bornes I1/I2/A sont présentes (voir photo)
Merci d'avance

**Comment by fairecasoimeme** [comment]
Bonjour,
si les bornes A i1 et I2 sont présentes, le ZLinky est compatible.

**Comment by PCluzz** [comment]
merci!
