### ISSUE TITLE
MAJ Non OTA sur nouvel hardware sans connecteur noir

### ISSUE THREAD

**Issue by tadikwa** [fairecasoimeme/Zlinky_TIC#232]
Hello,
je me permet d'ouvrir un ticket pour demander une précision par rapport à la mise à jour non ota sur le nouveau dongle.

En effet, depuis que je l'ai, il est bloqué en v1 (d'après mqtt sur home asssitant) je ne parviens pas à faire la maj en ota,
et je souhaitai le faire via le module usb ttl.

J'en ai maintenant un (même deux merci amazon).

Sauf que, j'ai pas vraiment envie de me lancer dans de la soudure, les connecteurs étant juste des trous, auriez vous une solution simple pour faire le contact provisoirement sans soudure pour faire la maj v13 ?

Un truc magique sur amazon pour connecter des trous en moins de deux ?

![image](https://github.com/fairecasoimeme/Zlinky_TIC/assets/6054289/d1daee55-9e68-4dd3-bfc8-aef160cd8a71)

`    "update": {
        "installed_version": 1,
        "latest_version": 13,
        "state": "available"
    },`

**Comment by JigSawFr** [comment]
Personnellement j'ai utilisé ça: Hailege 2pcs CP2102 USB 2.0 to TTL UART Serial Converter Module 5Pin STC PRGMR with Dupont Wire https://amzn.eu/d/2ySRu3R

Le tout en maintenant les broches dans les trous ;) sans soudures !

**Comment by florianbelhomme** [comment]
Attention Z2M/MQTT peuvent être menteur sur la version du firmware si vous aviez déjà associé le Zlinky par le passé.
Si vous avez effectué la MAJ du firmware et que vous avez eu un message de succès sur le logiciel de MAJ, mais qu'après ré-association vous voyez toujours le numéro de firmware précédent dans HA, voici une manip que vous pouvez tester pour être sûr :

- une fois le Zlinky associé
- sélectionnez le dans la liste des appareils
- cliquez sur l'onglet "console dev"
- dans "groupe de fonctionnalités" sélectionnez "genBasic"
- puis dans "attribut" sélectionnez "swBuildId"
- enfin cliquez sur le bouton vert "lire"

Z2M va demander en direct le numéro de version au Zlinky, elle va s'afficher en JSON en dessous du bouton. Comparez avec ce que vous attendiez puis avec ce que Z2M affiche dans les pages "user friendly".

CF : https://github.com/fairecasoimeme/ZiPulses/issues/21#issuecomment-1793840520

**Comment by tadikwa** [comment]
J'ai le même module. Cependant, c'est difficile d'obtenir un contact ok.
Je voyais sur l'autre ticket du ZiPulse, des gens galéré comme moi : https://github.com/fairecasoimeme/ZiPulses/issues/21

Je trouve compliqué d'arrivé à brancher la clef en tenant le module de travers pour faire contact tout en appuyant sur le bouton flash puis le relâchant en maintenant la clef et le module dans leur position.  J'ai juste le droit à un sapin de noël avec les voyants.

Savez qu'elle devrais être l'état des voyants du USBTTL au branchement ?

**Comment by fairecasoimeme** [comment]
Il est très probable que votre ZLinky soit déjà à jour. le plugin Z2M ne va pas chercher la bonne valeur de version au bon endroit.
Pour avoir la bonne version de votre appareil, il faut interroger manuellement le cluster : 0x0000 attribut : 0x4000. Si la valeur retournée est 4000-0013 c'est que vous êtes à jour. (ce qui est surement le cas car ça va bientôt faire un an que cette version a été release)

**Comment by tadikwa** [comment]
![IMG20240105113555](https://github.com/fairecasoimeme/Zlinky_TIC/assets/6054289/a0d1e04c-e5a6-411c-85a6-b1135a263171)
![IMG20240105114956](https://github.com/fairecasoimeme/Zlinky_TIC/assets/6054289/46e4e5de-6616-4a08-81c9-608716d7bec0)

j'ai testé avec mes p'tites rallonges mais toujours pareil, soit read error ou rien.

Si je branche la clef avec le branchement et le bouton flash appuyer alors j'ai aucun voyant.

Si je branche la clef sans appuyer sur flash, alors j'ai le tx en fixe et le RX qui fini par clignoter au bout de 5 secondes et tjrs le mm résultat read error au flash

**Comment by tadikwa** [comment]
Bon en effet si je lis via Z2M, le firmware semble déjà à jour.

![image](https://github.com/fairecasoimeme/Zlinky_TIC/assets/6054289/ff7223d1-e859-4c34-a3c3-216abd235a58)

**Comment by JigSawFr** [comment]
J'avais du inverser le sens du branchement sur la mienne et j'ai utilisé du scotch pour maintenir les contacts 🤣

**Comment by Dites33** [comment]
Hello

On pourrait ouvrir un ticket Z2M pour faire corriger le support et la lecture de la bonne valeur ? :)

**Comment by tadikwa** [comment]
> J'avais du inverser le sens du branchement sur la mienne et j'ai utilisé du scotch pour maintenir les contacts 🤣

J'ai testé d'inverser le tx et le rx (on ne sait jamais) mais non pas de résultat.

Au final, j'ai rebrancher le dongle, z2m doit surement se tromper sur la valeur à remonter pour le firmware installé.

Tant que ça marche c'est ok :)

**Comment by tadikwa** [comment]
> Hello
> 
> On pourrait ouvrir un ticket Z2M pour faire corriger le support et la lecture de la bonne valeur ? :)

Bonne idée.
En plus sur la nouvelle version 1.35.0 y'a des trucs en + pour le lixee

**Comment by fairecasoimeme** [comment]
D'après les captures d'écran (led bleu allumé sur le module TTL), je pense que vous avez grillé l'entrée RX du MCU (en faisant une mauvaise manip)
Vous pourrez mettre à jour OTA mais malheureusement, la mise à jour par USB ne pourra plus se faire.
Fred

**Comment by tadikwa** [comment]
Ok, par contre j'ai testé avec deux modules USB TTL neuf et les deux ont le même comportement.

De toute façon j'abandonne la MAJ et j'ouvre un ticket chez Z2M pour l'histoire de remontée de version
