### ISSUE TITLE
ZLinky ne s'allume pas

### ISSUE THREAD

**Issue by philuxe** [fairecasoimeme/Zlinky_TIC#238]
Bonjour,

Je viens de recevoir le module mais ce dernier ne s'allume pas:

![IMG_3054](https://github.com/fairecasoimeme/Zlinky_TIC/assets/16466030/98395a48-6968-47ff-8565-e0d3046f8d04)

que faut il faire ?

**Comment by philuxe** [comment]
j'ai tenté la mesure avec un multimètre mais je pense que les sondes sont trop epaisses pour faire contact donc forcément 0 courant.

du coup j ai essayé de plugin le Zlinky dans un autre Linky et ca ne marche pas non plus, tjs pas de LED


![IMG_3056](https://github.com/fairecasoimeme/Zlinky_TIC/assets/16466030/5dc8ad6f-914e-444f-9beb-701d7aaae97d)

**Comment by ketourneau** [comment]
J'ai le même problème avec le ZLinky reçu hier. Il ne s'allume pas non plus.

**Comment by ketourneau** [comment]
Je pense que c'est en lien avec #236

**Comment by ketourneau** [comment]
J'ai contacté EDF qui va faire la demande à ENEDIS pour passer la prise TIC du Linky en mode "Standard" à voir si ça corrige le problème.

https://particuliers.engie.fr/aide-contact.html?question=comment-changer-le-mode-de-fonctionnement-de-mon-compteur

**Comment by philuxe** [comment]
recu nouveau module, il s'allume correctement

**Comment by ketourneau** [comment]
Après avoir vérifié avec un voltmètre j'ai bien une tension. Le boîtier zlinky est donc défectueux, quel est la procédure pour un échange ?

**Comment by hichamC31300** [comment]
Bonjour
Je rencontre le même problème. Tension de 16V aux bornes du Linky. Mon zlinky reste quand même éteint. Pensez-vous qu'il est défectueux ?
