### ISSUE TITLE
Timeout sur la configuration du reporting sur le cluster 0x0702 et l attribut 0x0000

### ISSUE THREAD

**Issue by d3v2a** [fairecasoimeme/Zlinky_TIC#24]
L'attribut est marqué comme reportable mais le module ne répond pas à la demande de configuration 

passerelle : conbee II
application: zigbee2mqtt avec home assistant

|Commande TIC|CLUSTER|Attribut|Droit|Comment|data type|size max|unit|designation|valeur par defaut|
|------------|-------|--------|-----|--------------|---------|-------|----|-----------|------------|	
|![#f03c15](https://via.placeholder.com/15/f03c15/000000?text=+) BASE|0x0702|0x0000|RP||Uint32|9 car|Wh| Index Base|0|

Je ne sais pas si c est possible, ce serait intéressant d'avoir aussi les autres index (0x0100, 0x0102, etc.) en reportable

**Comment by fairecasoimeme** [comment]
Oui sur la version actuelle quand on fait un config report sur ces valeurs on a en retour le code erreur 0x8c mais le ZLinky prend quand même la demande.

Sur la prochaine version, le retour du config report sera en "success"

**Comment by ElieLiabeuf** [comment]
Hello @fairecasoimeme avez-vous une date pour cette release ? Ca semble être le point bloquant pour avoir une rémontée dans home assitante (voir : https://github.com/fairecasoimeme/Zlinky_TIC/issues/18)

**Comment by fairecasoimeme** [comment]
Sur la dernière version 4. Tous les éléments demandés sont reportables
