### ISSUE TITLE
Pas de remontée de IINST2 et IINST3 sur une installation triphasée

### ISSUE THREAD

**Issue by Nilan464** [fairecasoimeme/Zlinky_TIC#253]
Bonjour,

Avant j'utilisais le module avec Jeedom et ça fonctionnait parfaitement.
Mais depuis mon passage à Home Assistant je ne récupère plus toutes les valeurs.

Voici la configuration dans Zigbee2MQTT.

<img width="1453" alt="Capture d’écran 2024-04-04 à 15 09 07" src="https://github.com/fairecasoimeme/Zlinky_TIC/assets/155403807/b5542dbd-e805-424e-99dd-2fc3d551a8b6">

L'historique de IINST1 est bien récupéré :

<img width="558" alt="Capture d’écran 2024-04-04 à 15 10 35" src="https://github.com/fairecasoimeme/Zlinky_TIC/assets/155403807/5bbd4c92-5566-44a4-84f7-25d1f7e9ddeb">

Mais aucun historique sur INNST2 et INNST3.
Les deux m'indiquent une valeur de 3A et ça n'a pas bougé depuis une semaine.

<img width="558" alt="Capture d’écran 2024-04-04 à 15 12 08" src="https://github.com/fairecasoimeme/Zlinky_TIC/assets/155403807/719e37ae-0616-4911-83bd-420b97f839f5">

Je viens de redémarrer HA donc ne vous fiez pas à la mention "il y a 5 minutes".
Avant redémarrage il indiquait une semaine.

Je ne sais plus quoi faire.
Si vous avez des idées n'hésitez pas.

Merci.

**Comment by fairecasoimeme** [comment]
Bonjour,

Avez-vous tenter de supprimer et refaire l'appairage ?
il est possible que certaines requêtes ne soient pas passé.
