### ISSUE TITLE
Arrêts quotidien du module

### ISSUE THREAD

**Issue by djsyl** [fairecasoimeme/Zlinky_TIC#26]
Bonjour, depuis que j'ai mis en service le module lixee
régulièrement chaque nuit (3) le module arrête d'envoyer des données.

je suis obligé pour le faire repartir d'aller au compteur (pas d'affichage led)
de le déconnecter puis de le reconnecté pour qu'il reparte.

J'aimerai bien trouver une solution.

Merci bonne journée

**Comment by fairecasoimeme** [comment]
Si la LED est éteinte c'est qu'il y a un problème matériel.
Veuillez prendre contact ici : contact[at]lixee.fr

**Comment by djsyl** [comment]
Merci
Email envoyé !
