### ISSUE TITLE
Abonnement Zen Fixe (HC/HP)

### ISSUE THREAD

**Issue by achlyss-8** [fairecasoimeme/Zlinky_TIC#261]
Bonjour,

Je ne vois pas l'abonnement Zen Fixe avec option HC/HP dans la liste des tarifs. Il s'agit d'un abonnement classique HC/HP avec des tarifs réduits.

Mon Zlinky n'expose aucune donnée (pourtant dans state j'ai bien de la data), je suis en mode historique. Est-ce que je dois passer en mode standard pour cet abonnement ?

![Capture d’écran 2024-05-17 à 12 15 48](https://github.com/fairecasoimeme/Zlinky_TIC/assets/127400436/ce2207e3-6e14-4694-a0bd-e438e557bc7f)

![Capture d’écran 2024-05-17 à 12 15 54](https://github.com/fairecasoimeme/Zlinky_TIC/assets/127400436/7c76dc10-2016-4b01-8cac-da596d603eb4)

Je suis sur Z2M sous docker.

Merci

Edit : Je viens de faire la demande pour passer en mode standard, on verra si ça change quelque chose

**Comment by fairecasoimeme** [comment]
Bonjour,
Concernant l'abonnement, il faut se rapprocher des développeurs du plugin Z2M
Pour avoir les index concernant au plage tarifaire, il faut que vous passiez en mdoe standard comme indiqué dans la FAQ : 
https://github.com/fairecasoimeme/Zlinky_TIC/blob/master/README.md#1-jai-chang%C3%A9-dabonnement-et-je-ne-retrouve-plus-mes-index-dans-mon-dashboard-domotique
