### ISSUE TITLE
Erreur récurrente dans Z2M : `Failed to read zigbee attributes: Error: ZCL command 0x00158d0005d25e9d/1 liXeePrivate.read(["currentPrice","currentTarif","message1","message2"]`

### ISSUE THREAD

**Issue by MilesTEG1** [fairecasoimeme/Zlinky_TIC#266]
Bonjour,
J'ai depuis quelques temps ces erreurs dans Z2M :

```
Failed to read zigbee attributes: Error: ZCL command 0x00158d0005d25e9d/1 liXeePrivate.read(["currentPrice","currentTarif","message1","message2"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed ({"target":2695,"apsFrame":{"profileId":260,"clusterId":65382,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":30},"zclSequence":77,"commandIdentifier":1} timed out after 10000ms)

Failed to read zigbee attributes: Error: ZCL command 0x00158d0005d25e9d/1 liXeePrivate.read(["currentPrice","currentTarif","message1","message2"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed ({"target":2695,"apsFrame":{"profileId":260,"clusterId":65382,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":97},"zclSequence":14,"commandIdentifier":1} timed out after 10000ms)

Failed to read zigbee attributes: Error: ZCL command 0x00158d0005d25e9d/1 liXeePrivate.read(["currentPrice","currentTarif","message1","message2"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed ({"target":2695,"apsFrame":{"profileId":260,"clusterId":65382,"sourceEndpoint":1,"destinationEndpoint":1,"options":4416,"groupId":0,"sequence":21},"zclSequence":133,"commandIdentifier":1} timed out after 10000ms)
```

J'utilise l'add-on Zigbee2MQTT dans HAOS

### Zigbee2MQTT version

1.38.0 

### Adapter firmware version

7.4.3 [GA]

Même chose avec la 7.4.1 [GA]

### Adapter

HA SkyConnect with ember driver

### Setup

Add-on dans Home Assistant OS sur un NUC à base d'Intel

Je ne suis pas le seul à avoir ces erreurs, mais personne n'arrive à dire qui est en cause : Z2M ou le ZLinky.

Peut-être aurais-je plus de chance ici.

PS : je précise que mon ZLinky est en firmware limited v13, et qu'il y a plusieurs prises connectées Zigbee pas loin.
Voilà un schéma de mon maillage:
![CleanShot 2024-06-03 at 11 09 17@2x](https://github.com/fairecasoimeme/Zlinky_TIC/assets/29298312/ac701906-33a2-42df-9487-196e876be3a3)

Le ZLinky est bien connecté avec un LQI satisfaisant.

**Comment by fairecasoimeme** [comment]
Bonjour,

Les messages d'erreurs semblent être des "timeout" sur une demande d'info.
Apparemment, le timeout est systématiquement sur "currentPrice","currentTarif","message1","message2"
Pour savoir si c'est un des attributs qui ne réponds pas, il faudrait utiliser la console et faire une requête sur chacun des attributs

**Comment by MilesTEG1** [comment]
Bonjour @fairecasoimeme 

Avec la console dev, 
- currentPrice seul : pas de soucis
- currentPrice + currentTarif : pas de soucis
- currentPrice + currentTarif + message1 : problème (timeout)
- currentPrice + currentTarif + message2 : pas de soucis
- currentPrice + currentTarif + message1 + message2 : problème (timeout)
- message1 : pas de soucis
- message1 + message2 : pas de soucis

C'est bien l'ajout de message1 qui pose problème.



![CleanShot 2024-06-04 at 15 35 29@2x](https://github.com/fairecasoimeme/Zlinky_TIC/assets/29298312/91cda22f-9804-4ca6-9f45-4b68b0fcc87a)



> Il faut peut-être jouer avec le Meausrement poll chunk pour limiter le nombre d'attribut à poll en même temps.

Comment je fais cela ? Je veux dire, je mets quoi comme valeur ?
![image](https://github.com/fairecasoimeme/Zlinky_TIC/assets/29298312/14b7a5e2-b183-4b4d-ae2c-55136102c34c)

**Comment by fairecasoimeme** [comment]
je ne suis pas expert mais de ce que je comprends, c'est que le paramètre permet de faire des demandes d'attributs par paquet.
dans votre cas, je forcerais à 1. ce qui est étrange car, apparemment c'est la valeur par défaut mais on voit bien qu'il fait des demandes par 4

**Comment by MilesTEG1** [comment]
> je ne suis pas expert mais de ce que je comprends, c'est que le paramètre permet de faire des demandes d'attributs par paquet. dans votre cas, je forcerais à 1. ce qui est étrange car, apparemment c'est la valeur par défaut mais on voit bien qu'il fait des demandes par 4

Oh ! Il ne semble plus y avoir ces erreurs-là !!
Top, merci :)

En revanche, l'erreur du timeout persiste dans la console dev comme précédemment :)

**Comment by fairecasoimeme** [comment]
si dans le console dev, vous faites 4 demandes, le chunck n'intervient pas

**Comment by MilesTEG1** [comment]
> si dans le console dev, vous faites 4 demandes, le chunck n'intervient pas

Ok, je comprends mieux, et je m'en doutais du coup ^^
Merci pour votre aide.
