### ISSUE TITLE
Possibilité de désactiver la LED bleue

### ISSUE THREAD

**Issue by WoodyTheWoo** [fairecasoimeme/Zlinky_TIC#27]
Bonjour,

Est-ce qu'il serait possible de proposer la désactivation de la LED bleue en façade du module svp ?

Le choix de l'état logique (inversé ou non) de cette LED au travers d'un interrupteur virtuel Zigbee serait parfait.

D'avance, merci.

**Comment by fairecasoimeme** [comment]
Bonjour,
L'objectif pour cet appareil est de passer la labelisation enedis.
Et pour avoir ce label, la gestion de la LED est très importante. Voici un extrait de l'annexe du document Enedis-NOI-CPT_02E.pdf 
![image](https://user-images.githubusercontent.com/22256438/142244589-3bd6798d-5062-4654-acc5-0a27a19b40ee.png)

**Comment by WoodyTheWoo** [comment]
Bonjour,
Merci pour votre réponse rapide, en effet je comprends, pas de soucis.
Je tâcherai de regarder dans le code et de compiler une version qui correspond à mon besoin alors :)
