### ISSUE TITLE
Question : les ports I1 et I2 sont déjà utilisés, installation possible d'un ZLinky_TIC ?

### ISSUE THREAD

**Issue by papylhomme** [fairecasoimeme/Zlinky_TIC#270]
Bonjour,

désolé je pose ma question ici je n'ai pas trouvé de renseignements ailleurs sur le sujet.

Mon compteur Linky possède déjà un câble branché sur les ports I1 et I2, j'ai vu que certains ERL avait un port spécial qui faisait office de pont, est-ce le cas du ZLinky ?

Sinon est-il possible de le brancher en même temps que le câble directement sur le Linky ? Est-ce que quelqu'un a déjà tenté ca, pas de problème d'interférence à prévoir ?

**Comment by fairecasoimeme** [comment]
Bonjour,

oui il est possible de brancher en parallèle jusqu'à 5 appareils. 

Fred
