### ISSUE TITLE
Plus de remonté après MAJ v14

### ISSUE THREAD

**Issue by Sapherys** [fairecasoimeme/Zlinky_TIC#274]
Bonjour,

j'ai fait la MAJ OTA avec Z2M vers la version 14 aujourd'hui. 
Depuis, j'ai plus de remonté d'information. Actuellement j'ai en Whitelist seulement la donnée EAIT, ce qui me suffisait jusqe-là pour le suivi.
Est-ce que quelque chose à changé par rapport à ça pour que je n'ai plus de remonté dans HAOS?

![image](https://github.com/user-attachments/assets/f9392eb2-4345-4061-9992-4fd8b1ee50c2)

Un grand merci à vous si vous avez des pistes! :)

**Comment by Coldness00** [comment]
Salut, regarde la solution que j ai trouve sur le post:
https://github.com/fairecasoimeme/Zlinky_TIC/issues/256

**Comment by Sapherys** [comment]
> Salut, regarde la solution que j ai trouve sur le post: #256

Merci pour ta réponse. Quand tu dit "supprimer" tu veux dire disable? Parce que j'en ai une vraie tonne de lignes dans les rapports (et ca va encore plus bas):

![image](https://github.com/user-attachments/assets/a488ea1f-c893-4c2f-bd56-11185b90260a)

**Comment by Coldness00** [comment]
Oui, exactement.
Si ca ne marche pas, tu peux faire un re-appareillage et tout reviendra comme sur le screenshot

**Comment by graelo** [comment]
@Sapherys n'oublie pas stp de nous dire si ça marche pour toi, merci bcp.

**Comment by MilesTEG1** [comment]
Je referais un appairage et ensuite un reboot de Z2M.

**Comment by Sapherys** [comment]
> Oui, exactement. Si ca ne marche pas, tu peux faire un re-appareillage et tout reviendra comme sur le screenshot

Malheureusement ça n'a pas fonctionné chez moi, même avec un redémarrage Z2M. Je vais faire un ré appareillage en rentrant  pour voir si ça change quelque chose.
Mais déjà si d'autres ont le souci, c'est que ça ne vient pas de mon zlinky, c'est rassurant. J'en ai perdu 1 il y a 2 jours, plus de led, plus rien 😅

**Comment by Coldness00** [comment]
Je te recommande d'attendre au moins quelques heures avant d'etre sur.
Et il faut generalement le laisser debrancher 30min avant de le reconnecter suite a un changement.
Assures toi d'etre aussi dans le bon mode Historique / Standards ?

**Comment by Sapherys** [comment]
MAJ du jour: Pas de nouvelles remontés, même avec un appareillage pour l'instant.

**Comment by graelo** [comment]
Ok, merci pour ton retour d'exp (et navré).

**Comment by Sapherys** [comment]
> Je referais un appairage et ensuite un reboot de Z2M.

Ca a fonctionné chez toi?

**Comment by MilesTEG1** [comment]
> > Je referais un appairage et ensuite un reboot de Z2M.
> 
> 
> 
> Ca a fonctionné chez toi?

Je ne suis pas confronté à ce souci avec la v14.
C'était une suggestion 😊
Mais en général si tu modifies une options de paramètres spécifique dans Z2M, il faut le redémarrer.

**Comment by Sapherys** [comment]
De mon coté il a fallu faire une suppression du Zlinky dans Z2M puis un réapareillage. EN le renommant à l'identique, j'ai pas eu à reconfigurer le panneau des énergies. Ca fonctionne maintenant de nouveau et j'ai beaucoup moins de choses dans "Rapport" qu'avant.

**Comment by SBRK** [comment]
Chez moi, j'ai du refaire interview + reconfigure du device dans Z2M et ça a ajouté plein de trucs dans Reporting et depuis ça marche
