### ISSUE TITLE
mise à jour v14

### ISSUE THREAD

**Issue by am11r** [fairecasoimeme/Zlinky_TIC#279]
Bonjour,

J'ai finalement fait la mise à jour via USB TTL.
sous Z2M j'ai maintenant:
![Capture d’écran 2024-09-10 à 20 50 59](https://github.com/user-attachments/assets/b89ecc23-fac0-43fb-9fa0-6629d834917f)

mais sous HA paramètres:
![Capture d’écran 2024-09-10 à 20 57 46](https://github.com/user-attachments/assets/00c1df23-11b5-405f-895b-f5f56ebe4f89)

D'ou ma question, suis je bien en version 14? si oui pourquoi il m'est affiché version 1?

Merci à vous

**Comment by MilesTEG1** [comment]
Salut 
Tu as flashé quelle version du firmware v14 ? La standard ou la limited ?

**Comment by am11r** [comment]
salut,
j'ai été en standard, puis fais en limited et revenu en standard. J'ai meme fais en flashsant ou simple mise à jour mais cela n'a rien changé au final...

**Comment by MilesTEG1** [comment]
Donc tu es en standard.
Tu as flashé avec l'usb et ensuite as tu essayé de flasher avec Z2M ?
Car moi après avoir flashé la v14 standard en usb , Z2M m'a dit de le mettre à jour : je l'ai fait et ça s'est fini correctement et indique la version v14.

**Comment by am11r** [comment]
Oui tout pareil mais toujours v1….

**Comment by am11r** [comment]
je viens de retenter et la barre bleue défile encore te encore avant que tout revienne à l'etat initial: version installé V1, disponible v14.... grrrr....

**Comment by fairecasoimeme** [comment]
Il y a un bug sur Z2M qui ne va pas chercher la bonne valeur de la MAJ quand le ZLinky est flashé par USB. Donc vous êtes bien en V14. la version du firmware vous indique bien 4000-0014
