### ISSUE TITLE
firmware v14 router ZHA compteur en Wh mais affiché en kWh

### ISSUE THREAD

**Issue by Nbird67** [fairecasoimeme/Zlinky_TIC#281]
Bonjour à tous,

Depuis que j'ai passé mon firmware de v13 à v14 (j'avais un quirk donc reappairé), j'ai la remonté des compteurs kWh qui est passé en Wh en valeur mais est en kWh dans ZHA Home Assistant, ce qui a foutu une merde pas possible dans mon dashboard "energies".

Une idée de comment contourner le pb ?, j'ai déja tenté un reapparaige et une reinit (10s sur le bouton reset), rien à faire mes valeurs sont en Wh reconnue kWh dans ZHA...
cf un exemple pour HC et HP 1 605 825,0 kWh et 2 441 579,0 kWh (au lieu de 1605 et 2441).

Merci de votre aide.

Boris

**Comment by fairecasoimeme** [comment]
Bonjour,

Désolé mais aucun lien avec le firmware. Vous devriez revoir vos scripts ou paramétrages.


Fred
