### ISSUE TITLE
Pas de remontées des EASF01 & EASF02

### ISSUE THREAD

**Issue by Stef33fr** [fairecasoimeme/Zlinky_TIC#296]
Bonjour,

Depuis une semaine je n'ai plus de remontées de 
![image](https://github.com/user-attachments/assets/072d933a-4d26-4728-93f7-b6dc8e29e4fc)
ni de 
![image](https://github.com/user-attachments/assets/66ead824-64ed-4ffd-9339-973907229a9f)

Alors que toutes les autres données sont bien dynamique comme le courant, la tension, la charge active et la puissance apparente.

**Comment by julll190** [comment]
Dans Z2M, onglet "paramètres (spécifiques)", vérifie que ton paramétrage est toujours bon (Linky mode, Energy phase, ...). Le mien a sauté lundi dernier, du coup j'avais certaines valeurs qui ne remontaient plus malgré l'avoir débranché puis rebranché.

**Comment by Stef33fr** [comment]
> Dans Z2M, onglet "paramètres (spécifiques)", vérifie que ton paramétrage est toujours bon (Linky mode, Energy phase, ...). Le mien a sauté lundi dernier, du coup j'avais certaines valeurs qui ne remontaient plus malgré l'avoir débranché puis rebranché.

Bonsoir, j'ai déja tout vérifié de ce coté et tout est OK
En revanche, et ce sans rien faire, j'ai récupéré EASF01 & EASF02
