### ISSUE TITLE
Only updates when peak electricity is increasing.

### ISSUE THREAD

**Issue by traylenator** [fairecasoimeme/Zlinky_TIC#299]
Once my zlinky_tic is added to the energy dashboard of home assistant I seem to only get regular measurements when
the peak electricity is increasing.

So I see all my off peak electricity in one lump once the peak electricity starts increasing.

Linky Peak is sensor.linky_hchp
Linky OffPeak is sensor.linky_hchc

![image](https://github.com/user-attachments/assets/35d645ef-a058-4183-8a39-b2333199f5f2)

I'd like to see the updates over night at hourly resolution.

**Comment by traylenator** [comment]
Here are the off peak meansurements:

![image](https://github.com/user-attachments/assets/ea0936e2-14b3-4e9e-a441-c97110381e6a)

Off peak starts at 02:00 but does not appear till the massive step at 06:00.

**Comment by steenlarsen** [comment]
Does this happen always? I had this problem sporadically a few releases back but now it never happens. Having said that I also had my Linky replaced because it was faulty and at some time stopped counting electricity completely.

**Comment by traylenator** [comment]
Indeed for whatever reason this situation has fixed itself now.
