### ISSUE TITLE
Possibilité de régler le reporting max sous les 60 secondes

### ISSUE THREAD

**Issue by KipK** [fairecasoimeme/Zlinky_TIC#302]
Salut @fairecasoimeme 

J'aimerais pouvoir régler le reporting max de Sinst sous les 60 secondes qui est la limite  logicielle pour l'instant.

Depuis quelques mois j'ai mon sinst réglé en reporting min sur 10s avec un changement minimum sur 1.
Cela fonctionne bien sur mon linky, j'ai bien sinst toutes les 10s.

Aujourd'hui je voudrais changer un truc pour avoir plus de reactivité sur les gros changements, et je me rend compte que la valeur reporting max est bloquée à 60 sec minium.

Je voudrais pouvoir regler le min reporting sur 1s, et le max sur 20s, avec une valeur de changement minimum de 500 pour que seules les changements de puissance > 500VA soient mis à jours immediatement et le reste à 20.
Au final ca ferait moins de messages à envoyer, avec le confort d'avoir bien les changements importants en quasi temps réél. 
J'ai testé déjà avec la limite actuelle, donc le max sur 61sec, le min sur 1sec, et changement min sur 1 et ca fonctionne impec.

Possible d'avoir ça pour la prochaine maj ? 

Merci à toi

**Comment by fairecasoimeme** [comment]
Bonjour,

Oui, je peux créer une version spécifique pour commencer avec cette modification et que tu puisses la tester.
De mémoire tu utilises une version limited ?

**Comment by KipK** [comment]
Top merci. 
Je suis en version standard maintenant.

**Comment by fairecasoimeme** [comment]
ok je compile une version asap

**Comment by fairecasoimeme** [comment]
J'ai pas pu tester mais normalement c'est ok

[ZLinky_router_v14_MAX_Report.zip](https://github.com/user-attachments/files/18009852/ZLinky_router_v14_MAX_Report.zip)

**Comment by KipK** [comment]
Merci d'avoir pris le temps pour ça.

Apperement ca ne passe pas, si je mets une valeur inférieure à 61 pour "Max rep Interval" sur SINST, il renvoie toujours la même erreur:

`z2m: Request 'zigbee2mqtt/bridge/request/device/configure_reporting' failed with error: 'ZCL command 0x00158d000638e0dc/1 haElectricalMeasurement.configReport([{"attribute":"apparentPower","minimumReportInterval":1,"maximumReportInterval":20,"reportableChange":500}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"reservedBits":0,"writeUndiv":false}) failed (Status 'INVALID_VALUE')'`

**Comment by fairecasoimeme** [comment]
erf OK
Je vais faire plus de tests ASAP alors

**Comment by fairecasoimeme** [comment]
oui c'est exactement ce que j'ai fait en modification mais apparemment ça ne suffit pas. Il faut que j'investigue plus

**Comment by KipK** [comment]
> oui c'est exactement ce que j'ai fait en modification mais apparemment ça ne suffit pas. Il faut que j'investigue plus

Et tu avais définis aussi

`ZCL_ATTRIBUTE_REPORTING_SERVER_SUPPORTED`
?

**Comment by fairecasoimeme** [comment]
Oui, c'est plus un problème (je pense) de timer. je cherche actuellement, mais je pense qu'il doit y avoir un timer à 60 sec quelque part qui bloque. je cherche par rapport à l'erreur retournée : E_ZCL_ERR_INVALID_VALUE

**Comment by fairecasoimeme** [comment]
Normalement c'est ok. 
[ZLinky_router_v14_MAX_Report2.zip](https://github.com/user-attachments/files/18048016/ZLinky_router_v14_MAX_Report2.zip)

**Comment by KipK** [comment]
C'est tout bon 👍 Merci

**Comment by fairecasoimeme** [comment]
C'était juste la compilation qui ne prenait pas en charge mon fichier .h :) 
As-tu un retour sur le fonctionnement de ton nouveau reporting ?

**Comment by KipK** [comment]
oui ca fonctionne impec. J'ai bien la remontée SINST en instantané pour ce qui est superieur à 500VA et un refresh toutes les 20s dans tout les cas. 
Ca change pas mal la donne, je n,'arrive plus à faire sauter le compteur avec la borne de recharge maintenant :)

**Comment by fairecasoimeme** [comment]
👍
