### ISSUE TITLE
maj firmware via usb ttl

### ISSUE THREAD

**Issue by chrisalex-dev** [fairecasoimeme/Zlinky_TIC#35]
bonjour,
je ne parviens pas à inclure le Zlinky_TIc sous Jeedom avec plug in zigbee et cle popp.
j'aimerai tenter de mettre à jour le firmware via usb tll mais je ne comprend pas quel est le fichier firmware à utiliser, selon mon niveau de compréhension ce serait celui de la zigate à savoir le ZiGatev2-321.bin? pourvez vous confirmer cela?
merci

**Comment by seblang** [comment]
Hello le firmware est la:

https://github.com/fairecasoimeme/Zlinky_TIC/releases/tag/V1.0

En revanche c'est la même méthode que la zigate !
Seb

**Comment by chrisalex-dev** [comment]
merci de l'info
