### ISSUE TITLE
Wrong Date type

### ISSUE THREAD

**Issue by vk496** [fairecasoimeme/Zlinky_TIC#38]
Hello,

The attribute date (0xFF66/0x0202) is a String limited to 10 chars for representing a custom Enedis date format (H**081225**_223518_)

However, the zlinky device only transmit 10 chars (H**081225**_223_). 3 chars are missing.

**Comment by fairecasoimeme** [comment]
hello,
 fixed on new v3 release

**Comment by vk496** [comment]
@fairecasoimeme in the v3 firmware the DATE is reported as weird number with nulls inside: 02\null061182025\null

**Comment by fairecasoimeme** [comment]
fixed with next version
