### ISSUE TITLE
Is Identify Cluster available

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#4]
Is Cluster Identify available and supported ? What are the commands which can be used

**Comment by fairecasoimeme** [comment]
Not tested

**Comment by pipiche38** [comment]
so why enabling CLuster 0003 ?

**Comment by fairecasoimeme** [comment]
In aim to verify if a short address correspond to the device.
Normally if an identify is requested ZLinky_tic will play with its LED to say hello.
The function is under dev
