### ISSUE TITLE
Arrêt de communication fréquente 

### ISSUE THREAD

**Issue by seblang** [fairecasoimeme/Zlinky_TIC#42]
Bonjour, 

Cela fait maintenant quelques temps que j'utilise le zlinky-tic et jusque là il marchait très bien. 

Une utilisation avec z2m sous ha. 

Seulement depuis une semaine il arrête d'émettre régulièrement. La led bleue reste fixe comme si tout allait bien avec le contrôleur mais celui ci ne reçoit plus d'informations et des interrogations dans la console dev retourne une erreur de non réponse. 

Une déconnexion du module avec quelque minutes d'attente avant reconnexion resou le soucis mais pour une durée plus ou moins variable de renfonctionnement ! 

D'où vient le problème ?
Une solution ?

**Comment by Crocmagnon** [comment]
J'ai également la même configuration et le même problème. J'attends avec impatience cette PR : https://github.com/Koenkk/zigbee-herdsman-converters/pull/3493

**Comment by pdecat** [comment]
J'ai un problème similaire niveau commandes et attributs, mais ma LED s'éteint complètement par contre. :confused:

**Comment by fairecasoimeme** [comment]
Pour le problème de coupures d'alimentation, nous avons avancé et une modification matérielle permet de limiter les problèmes.
contactez-moi par mail : contact[at]lixee.Fr

**Comment by 0r1g1ne** [comment]
Bonjour, j'ai le même problème. La led s'éteint, la communication s'interrompt. Je vous ai envoyé un mail à contact(at)lixee.fr. Merci d'avance.

**Comment by guix77** [comment]
Comment faites-vous marcher le Z_Linky avec z2m sachant que la PR n'est pas mergée? Sauf si bien sûr vous utilisez la PR telle qu'elle.

**Comment by Crocmagnon** [comment]
Je viens également d'avoir le problème de l'alimentation qui s'éteint. Je vous envoie un mail.

**Comment by AdrienBigot** [comment]
Idem, de mon côté le module s'éteint régulièrement. Ca me rassure de voir que je ne suis pas le seul dans ce cas.

**Comment by pdecat** [comment]
Les problèmes de communication sont résolus pour moi [avec la modification apportée par @fairecasoimeme à mon module ZLinky_TIC](https://github.com/fairecasoimeme/Zlinky_TIC/issues/48#issuecomment-1027767123).
