### ISSUE TITLE
Problème flash firmeware

### ISSUE THREAD

**Issue by seblang** [fairecasoimeme/Zlinky_TIC#43]
Bonjour

j'ai essayé de flasher mon Zlinky pour la mise a jour au dernier firmeware mais impossible!

J'ai suivi la procédure :
- utilisation d'un USB TTL en CP2102 (driver installé et usb ok)
- j'ai ensuite branché mon Zlinky dessus et branché l'USB a mon PC en maintenant la touche "Flasch enfoncé"
- Mon pc a fait un son et l'usb a affiché une lumière rouge
- J'ai ensuite lancé une console powershell
- je me suis mis dans le répertoire C:\NXP\DK6ProductionFlashProgrammer
- et j'ai lancé la commande ./DK6Programmer -s COMXX -P 500000 -Y -p C:\Users\Sebastien\Downloads\zlinky\ZLinky_router_v3.0.bin

Mais le programme me remonte ceux-ci

![lixee20](https://user-images.githubusercontent.com/11487773/149488569-b1ee9d8a-afd3-47b1-bc1d-5ecef3ac0b0f.JPG)

Une idée ?
merci

**Comment by fairecasoimeme** [comment]
Ce n'est pas COMXX

les XX correspondent au numéros du port. Il faut aller dans le gestionnaire de périphériques pour avoir le numéro.
