### ISSUE TITLE
MAJ OTA avec Domoticz et PiZiGate V2 ?

### ISSUE THREAD

**Issue by dranreb38** [fairecasoimeme/Zlinky_TIC#45]
Bonjour, 

Je ne possède pas de clé USB TTL CP2102, afin de mettre à jour le firmware en v4, peux t'on faire la MAJ en OTA avec domoticz ?, ou je dois forcement acquérir une clé USB / TTL

**Comment by zigbeefordomoticz** [comment]
je te recommande de venir sur le forum Domoticz .
https://easydomoticz.com/forum/viewforum.php?f=28&sid=41179ed98ef4f8795637e46cc205fdcd

Tu trouveras egalement beaucoup d'information ici:
https://github.com/zigbeefordomoticz/wiki/blob/master/fr-fr/Home.md

**Comment by dranreb38** [comment]
Merci, mais entretemps j'ai commandé une clé USB TTL CP2102. 
Donc mise à jour faite, je suis bien en firmware 4 mais, depuis après de nouveau un appareillage je ne reçois plus de données en historique comme auparavant.
![Screenshot_31](https://user-images.githubusercontent.com/16446911/151769066-60a368d2-c364-403b-89a4-5748ed39c98d.jpg)

![Screenshot_28](https://user-images.githubusercontent.com/16446911/151769129-29a164b4-f231-4951-8ebe-29d237b9391a.jpg)

![Screenshot_29](https://user-images.githubusercontent.com/16446911/151769085-55603e54-30a3-4861-943b-bd9cbe40b2ae.jpg)
![Screenshot_30](https://user-images.githubusercontent.com/16446911/151769150-1a3dd615-560e-4330-a2a1-a7db87aabe91.jpg)

 Je n'ai en graphe que le cluster **ZLinky_TIC_Power & ZLinky_TIC_Ampere3** d'ailleurs le graphe ZLinky_TIC_Ampere3 ne correspond pas à des ampères  ou VA
