### ISSUE TITLE
Augmenter la portée du Zlinky

### ISSUE THREAD

**Issue by bensaeba** [fairecasoimeme/Zlinky_TIC#47]
Bonjour à tous,

Plus une question trucs et astuces qu'un bug mais je voudrais savoir s'il est possible d'augmenter la portée du Zlinky avec une antenne déportée qui sort du coffret EDF.
A priori c'est possible, je vois que @pdecat l'a fait ici : https://github.com/fairecasoimeme/Zlinky_TIC/issues/19#issuecomment-1003382649
Idéalement j'aimerais faire la même chose :)
Est-qu'il serait de fournir un tuto svp?
Je pensais que la portée du zigbee serait suffisamment puissante mais mon compteur triphasé est en limite extérieure de propriété dans le coffret EDF à environ 30 mètre de mon zaspeberry+zigate+ usb est visiblement trop loin/protégé.

Merci bcp!
Ben

**Comment by pdecat** [comment]
L'antenne que j'ai est celle fournie [en option sur la boutique officielle Lixee](https://lixee.fr/produits/37-72-zigate-usb-ttl-3770014375148.html#/26-antenneexterne-oui) :
![image](https://user-images.githubusercontent.com/318490/150187442-6b37fe0e-d68d-4b22-86ba-60556f5258e9.png)

**Comment by bensaeba** [comment]
Hello, 
Merci pour le retour. Je n'avais pas vu cette option.
Désolé pour la question ...

**Comment by pdecat** [comment]
Pas de soucis, il y a peut-être un moyen d'en ajouter une soi-même.

**Comment by fairecasoimeme** [comment]
Nop pas moyen de faire les modifs soit même sauf si on maitrise la soudure et les composants en 0402 de dimension.

**Comment by bdherouville** [comment]
Bonjour,

je viens de commander un lixee sans antenne pour remplacer mon précédent qui a pris l'eau pensant que le connecteur y était. Est-ce possible de savoir si il y a plusieurs composants à ajouter ?

**Comment by fairecasoimeme** [comment]
Voici la marche à suivre pour rajouter l’antenne externe : 
 
 
![image](https://github.com/user-attachments/assets/2ce82d87-bc48-4212-bf0d-48c76d1019ec)

 
1.	Faire une rotation du condensateur de 90° vers la gauche.
2.	Souder un connecteur IPEX : ex : https://www.lcsc.com/search?q=GT-RF1125A-01
 
Grâce à cette modification, vous pourrez brancher votre antenne avec un câble ufl.

**Comment by Thelvaen** [comment]
hello,

Sans vouloir necro le post, quelle est la marche à suivre quand on a la board en v2.3 ?

c'est celui là que je dois faire tourner ?

<img width="3000" height="4000" alt="Image" src="https://github.com/user-attachments/assets/a43a4c54-a0f2-4d18-9c99-4d05ea2a5720" />

Je ne suis pas forcément à l'aise avec de si petits composants, mais j'ai déjà bricolé un peu avec du CMS, je comprends bien les conséquences sur la garantie également.

**Comment by fairecasoimeme** [comment]
Pour passer sur le mode antenne externe, il faut en effet déplacer ce condensateur et le tourner comme vous l'avez entouré et de l'autre face de la carte, souder un connecteur IPEX

**Comment by Thelvaen** [comment]
> Pour passer sur le mode antenne externe, il faut en effet déplacer ce condensateur et le tourner comme vous l'avez entouré et de l'autre face de la carte, souder un connecteur IPEX

Merci pour la réponse :)

Le connecteur IPEX/U.FL est déjà en place, donc je ne devrais pas avoir à le souder :)

Bon maintenant faut que je retrouve mon Kapton et ma station de soudure à air chaud ^^

**Comment by fairecasoimeme** [comment]
vaut mieux le faire au fer à souder

**Comment by Thelvaen** [comment]
du 0402, ça me parait trop petit ... ou alors faut que je commence à attacher une aiguille à la panne ?

J'ai peur de court-circuiter le condensateur si je fais ça au fer.
