### ISSUE TITLE
Utilisation d'une alimentation externe

### ISSUE THREAD

**Issue by pdecat** [fairecasoimeme/Zlinky_TIC#48]
Mon module ZLinky_TIC [arrêtant systématiquement de communiquer (et LED éteinte) au bout de quelques heures](https://github.com/fairecasoimeme/Zlinky_TIC/issues/42#issuecomment-1013297953) après avoir été branché, j'aimerais écarter la piste d'une alimentation trop faible due à la distance avec le reste de mon réseau Zigbee.

Est-il possible d'alimenter le module ZLinky_TIC avec une alimentation externe, au moins pour ces tests ?

PS: j'ai placé un routeur filaire (une [prise IKEA](https://zigbee.blakadder.com/Ikea_E1603.html)) juste au dessus du compteur et le ZLinky_TIC s'y connecte avec un LQI local de 255 entre les deux, mais cela ne change rien. Il essaie probablement de passer en direct pour obtenir un LQI total meilleur. La prise IKEA ne perd jamais la connexion elle.

![image](https://user-images.githubusercontent.com/318490/150193245-0dbd6acc-c3bd-4271-a3a7-8c35642acee3.png)

![image](https://user-images.githubusercontent.com/318490/150193032-0f42a972-23fb-4d77-81c3-a90e98890ab4.png)

**Comment by fairecasoimeme** [comment]
Salut,
pour régler le problème des coupures systématiques, j'ai surement une solution matérielle. Peux-tu me contacter par mail ?
Fred

**Comment by pdecat** [comment]
Hello @fairecasoimeme,

j'ai bien reçu le module ZLinky_TIC suite à ta modification, et je l'ai aussitôt branché. Pour le moment, tout est ok :crossed_fingers:

![image](https://user-images.githubusercontent.com/318490/152127535-c47343df-ee35-4d40-a887-81c175a61ac0.png)

Le LQI semble plus élevé, peut-être dû à la nouvelle position dans laquelle j'ai mis l'antenne.

En quoi consistait la modification par curiosité ?

**Comment by fairecasoimeme** [comment]
J'ai rajouté un condensateur et un superviseur de tension.

Fred

**Comment by pdecat** [comment]
So far, so good. Merci :)

![image](https://user-images.githubusercontent.com/318490/152174808-3cff514f-9b9c-49c4-be36-9c80577968f8.png)

**Comment by pdecat** [comment]
Je confirme que ça tout est ok désormais.
