### ISSUE TITLE
Cluster 0x0702 - Attributes 0x0301 and 0x0302

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#5]
Are Attributes 0x0301 and 0x0302 available on Cluster 0x702 in order to get the Multiplier and Divisor values ?
Having 0x0300 Attribute would also give the Unit of Measure

**Comment by fairecasoimeme** [comment]
These attributes are not used for this device. no multiplier and divisor values. 1 unit is 1 unit.
0x0300 is not used because this cluster have various unit.
