### ISSUE TITLE
Zlinky neuf, clignote 8 fois, puis 9 fois, et recommence

### ISSUE THREAD

**Issue by T0ytoy** [fairecasoimeme/Zlinky_TIC#51]
Bonjour, 

Je ne sais pas trop si une issue Github est le bon endroit pour poser la question, n'hésitez pas à me rediriger le cas échéant.
Ma Zlinky toute neuve se connecte sans soucis à Home Assistant, mais elle remonte toujours des valeurs aberrantes et qui ne changent jamais : 

![image](https://user-images.githubusercontent.com/18136751/153044041-cb6d99dc-8a72-45d6-86a0-5616559d2cf4.png)

Connectée au compteur Linky, la ZLinky clignote 8 fois, puis quelques secondes fixe, puis 9 fois, puis fixe à nouveau et recommence. Si j'en crois la documentation, elle devrait soit clignoter 4 fois, soit être tout le temps allumer, donc je ne sais pas quoi en penser?

J'ai également tenté de la mettre à jour avec le firmware 4 : le flash se passe bien sur un rpi 3B+ avec la commande suivante : 
`sudo ./DK6Programmer -s /dev/ttyUSB0 -P 115200 -Y -p ZLinky_router_v4.0.bin ZLinky_router_v4.0.bin`

mais l'affichage dans Home Assistant indique toujours une version 01... Y a-t-il un moyen de vérifier la version du firmware directement via l'utilitaire DK6Programmer par exemple ?
![image](https://user-images.githubusercontent.com/18136751/153044480-775d7c0b-45d1-48f4-9a96-7306d2838d54.png)

Est-ce un signe que l'appareil est défectueux, ou bien un problème de mon côté ? Pour info mon Linky est en mode historique, mais ça ne devrait pas poser de soucis.

EDIT : semble être semblable à l'issue #31 que je n'avais pas vu, je laisse mon issue ouverte et j'envoie en parralèle un mail à contact@lixee.fr, il est possible que ce soit un problème de matériel.

EDIT : un appel à l'attribue sw_build_id renvoie `4000-0004`, donc il semble que la maj du firmware se soit bien passé, au moins.

**Comment by fairecasoimeme** [comment]
Bonjour,
Si le ZLinky_TIC ne cesse de clignoter c'est qu'il n'arrive pas à décoder les données du Linky.
Contactez-moi par mail pour un échange standard.
Fred

**Comment by T0ytoy** [comment]
@fairecasoimeme mail envoyé hier soir à contact[AT]lixee.fr, merci d'avance ;)

**Comment by fairecasoimeme** [comment]
Désolé mais je n'ai rien reçu. Essayez sur contact[at]zigate.fr

**Comment by T0ytoy** [comment]
C'est renvoyé, merci ;)

**Comment by fairecasoimeme** [comment]
cette fois-ci, bien reçu

**Comment by T0ytoy** [comment]
Un A/R par la poste plus tard, le ZLinky fonctionne maintenant correctement et remonte des informations (testé sur 30 minutes pour le moment, sans soucis).
Merci !

**Comment by dansch1973** [comment]
Bonjour,
J'ai le même problème. Mon Zlinky neuf, clignote 8 fois, puis 9 fois, et recommence
Cdt,

**Comment by T0ytoy** [comment]
@dansch1973 problème réglé pour moi suite à un retour et réparation du zlinky. Il s'agissait à priori d'une diode mal soudée ou disfonctionnelle, je te recommande de contacter @fairecasoimeme ;)
