### ISSUE TITLE
Flashing using CP2102 without 3,3V

### ISSUE THREAD

**Issue by capi92** [fairecasoimeme/Zlinky_TIC#52]
Bonjour,

Est-il possible de flasher en usb avec un CP2102 qui est 5V uniquement (i.e. pas de 3,3 V)?
![image](https://user-images.githubusercontent.com/6361326/153558952-d017980e-b7ac-44e7-935a-2240c5d76f8a.png)

Merci de votre aide.

Cdt

**Comment by fairecasoimeme** [comment]
Non il faut du 3.3v pour flasher le ZLinky_TIC avec son port de prog
