### ISSUE TITLE
4 commandes seulement pour le ZLinky TIC avec Zigate sur Jeedom

### ISSUE THREAD

**Issue by echaplet** [fairecasoimeme/Zlinky_TIC#55]
Bonjour,
ayant acheté récemment un ZLinky TIC appairé à une Zigate, je n'obtiens que 4 commandes dispo.
- manufacturer
- type
- current_delivered
- refresh

Je ne vois pas ce qui cloche, c'est décevant pour un produit à 50€...
Un peu d'aide serait le bienvenue, merci !
Eric

https://community.jeedom.com/t/peu-de-commandes-pour-le-zlinky-tic-souci-matos-ou-plugin/78435

**Comment by fairecasoimeme** [comment]
Bonjour,

Sur jeedom, il faut utiliser le plugin officiel zigbee. 
Le plugin ZiGate n'est plus maintenu par son développeur. (Je ne suis pas le développeur)
Il y a aussi zigbee2mqtt avec zigbeelinker il me semble.
Voir peut-être avec la communauté Abeille pour voir la compatibilité avec le plugin

Fred

**Comment by echaplet** [comment]
fonctionnement ok avec le plugin officiel zigbee et la zigate mise à jour en OPDM
