### ISSUE TITLE
Fréquence de remontée des données ?

### ISSUE THREAD

**Issue by rgrunbla** [fairecasoimeme/Zlinky_TIC#57]
Bonjour,

À quelle fréquence maximale est il possible de remonter les données du Zlinky_TIC ? La TIC envoie un message à peu près toutes les deux / trois secondes: est-il possible d'interroger le Zlinky_TIC (si il fonctionne en pull) ou de lui demander de remonter ces données (si il fonctionne en push) à cette fréquence, ou cette fréquence est elle trop importante en regard de la puissance nécessaire pour ces messages ?

**Comment by fairecasoimeme** [comment]
Bonjour,
Le ZLinky_TIC réceptionne les données toutes les 7 secondes environs. Il peut être paramétré avec des rapports selon paramètres temporels par exemple(push) ou en polling.
Préférable d'interroger un cluster / propriété toutes les minutes (même si c'est possible de faire moins)
