### ISSUE TITLE
Certaines valeurs ne remontent pas

### ISSUE THREAD

**Issue by batchmanfr** [fairecasoimeme/Zlinky_TIC#59]
Bonjour,

En mode Standard Triphasé, je constate que seules certaines valeurs remontent dans Home Assistant (via Z2M) :
![image](https://user-images.githubusercontent.com/60405839/160704981-0980d7c1-be64-44f5-9ffb-4dc3fba675ef.png)

Donc aucune info sur la consommation en kWh... et par conséquent pas de suivi de la consommation dans l'onglet Energie de Home Assistant donc, même si j'imagine qu'une bidouille dans le style de ce que propose @skanx pour sha doit être possible (https://github.com/fairecasoimeme/Zlinky_TIC/issues/18#issuecomment-1021186192)

En cherchant bien, j'ai réussi à trouver la consommation totale dans les attributs d'états des différentes entités (exemple ici pour l'entité IRMS1) :
![image](https://user-images.githubusercontent.com/60405839/160706162-5c0022b7-2c39-42f7-96ad-a10f435897a0.png)
Mais l'info n'est pas identifiée comme entité à part entière, et surtout, je n'ai aucun détail (je suis en HP/HC, je devrais donc avoir selon la doc EASF01 pour le compteur HP et EASF02 pour le compteur HC)

Une idée de ce qui bloque ? Un paramétrage de la Zlinky ou du module Zigbee2MQTT?

Merci !

**Comment by fairecasoimeme** [comment]
Bonjour,
L'information EASF01 et EASF02 est nommé : 
currentTier1SummDelivered et currentTier2SummDelivered dans Z2M

vous pouvez vérifier si ces valeurs existent dans votre fichier.

Dans tous les cas cela ne concerne pas le ZLinky mais plutôt le module Zigbee2MQTT 

@vk496 une idée ?

**Comment by vk496** [comment]
@batchmanfr could you check what is exposed in Z2M (not Home Assistant)?

Standard+Triphase should report EASFXX as attribute

**Comment by vk496** [comment]
btw, did you forced the zlinky config acording to your linky and rebooted Z2M?

**Comment by batchmanfr** [comment]
Thx @fairecasoimeme @vk496 for your answer.

I've forced the zlinky config his way :
![image](https://user-images.githubusercontent.com/60405839/160921634-b44d4884-22e4-4400-ad65-6ef2b7ac6f8e.png)
Btw I've tried "auto" configuration and the values that show up in Z2M are the same.

This is what I see on the z2m logs :
`MQTT publish: topic 'zigbee2mqtt/ZLinky', payload '{"active_power_max":3599,"active_power_max_ph_b":4402,"active_power_max_ph_c":4162,"apparent_power":133,"apparent_power_ph_b":231,"apparent_power_ph_c":155,"average_rms_voltage_meas_period":235,"average_rms_voltage_meas_period_ph_c":234,"average_rms_voltage_measure_period_ph_b":235,"current_summ_delivered":48825.2,"current_tarif":"H PLEINE/CREUSE","drawn_v_a_max_n1":3465,"drawn_v_a_max_n1_p2":2017,"drawn_v_a_max_n1_p3":2979,"linkquality":90,"rms_current":1,"rms_current_ph_b":1,"rms_current_ph_c":1,"rms_voltage":236,"rms_voltage_ph_b":235,"rms_voltage_ph_c":233,"status_register":"003A4401","update":{"state":"idle"},"update_available":false}'`

So I've a `current_summ_delivered` value (that is not exposed in Z2M), but no EASFXX attribute :
![image](https://user-images.githubusercontent.com/60405839/160922655-def219fa-d2b0-4607-9fbc-785a5f1731f3.png)
![image](https://user-images.githubusercontent.com/60405839/160922717-078409be-a251-41a9-ac3e-2f36627098b9.png)

**Comment by batchmanfr** [comment]
Hi,
This issue have been resolved with Z2M version 1.25.0-1 released today.
Seems to be the @SilenT-FR pulls on zigbee-herdsman-converters repository that solved this :
https://github.com/Koenkk/zigbee-herdsman-converters/pull/3946
https://github.com/Koenkk/zigbee-herdsman-converters/pull/3950
https://github.com/Koenkk/zigbee-herdsman-converters/pull/3951

Thank you for your help. 

A bientôt !
Florian

**Comment by SilentT19** [comment]
your welcome

**Comment by SilentT-FR** [comment]
your welcome
