### ISSUE TITLE
Configure Reporting on Cluster 0x0b04 no response

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#7]
When seting Configure Reporting on Cluster 0x0b04 for attributes 0x0505, 0x0508, 0x050b we get no response from the device

**Comment by fairecasoimeme** [comment]
This should be OK for 0x0508 attribute not the other which are not manage

**Comment by pipiche38** [comment]
Sound good for 0x0508, 0x908, 0x0a08 and 0x050F
