### ISSUE TITLE
Compatibility with domoticz and zigbee receiver

### ISSUE THREAD

**Issue by BenGost** [fairecasoimeme/Zlinky_TIC#75]
Hello,

I couldn't get it to work properly with MQTT with a "CCxxx" key. I only have the network quality indicator.
I've been looking everywhere and can't find a clear explanation.

Can you tell me, if you managed to make it work with Domoticz?
What is the complete configuration of your domoticz?

Thanks

**Comment by pipiche38** [comment]
@BenGost it works with Domoticz with the ZigbeeforDomoticz plugin either via the zigpy radio librairies or the Zigate native one.
Only basic reporting works

For more complex especially Energy Production this is too complex as it looks we have to use the ZLinky in an other way.

<img width="1314" alt="Screenshot 2022-08-03 at 15 14 50" src="https://user-images.githubusercontent.com/8291674/182618177-4bb41ae4-ebb2-479a-9a1d-ef28bb9f9ce0.png">

**Comment by BenGost** [comment]
Thank you pipeche38! I will try that!

**Comment by pipiche38** [comment]
@BenGost did you try ?

**Comment by BenGost** [comment]
Hi @pipiche38 ,

Yes thank you it works!
