### ISSUE TITLE
Plus de remontées BASE depuis mise à jour v6

### ISSUE THREAD

**Issue by liambrugaro** [fairecasoimeme/Zlinky_TIC#88]
Bonjour,

depuis la mise à jour en version 6, ma valeur BASE (current_sum_delivered) est bloquée sur une valeur (21554kWh).
par contre je recois bien des informations (lqi, PAPP, etc)
j'ai tenté de débrancher/rebrancher le Zlinky_TIC, relancer zigbee2mqtt, le problème persiste.

j'ai une configuration plutot simple, un linky consommation uniquement avec abonnement 6 kVA.

Pouvez-vous m'aider ? 
n'hésitez pas si vous avec besoin d'informations de debug supplémentaires :)

**Comment by fairecasoimeme** [comment]
Bonjour,

Normalement pas de lien avec la version 6.  J'ai reçu votre mail et je pense que les coupures dont vous me parlez sont certainement liées au condensateur manquant.
La modification règlera le problème.
