### ISSUE TITLE
0x0B04 / 0x050A seems to report 2 differents values

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#9]
<img width="873" alt="Screenshot 2021-09-28 at 11 02 07" src="https://user-images.githubusercontent.com/8291674/135057276-f646d2ec-ee22-479c-be52-a896ec8be050.png">

**Comment by pipiche38** [comment]
Same for that one 

<img width="941" alt="Screenshot 2021-09-28 at 11 02 58" src="https://user-images.githubusercontent.com/8291674/135057415-6ca4f381-51a8-41b1-82a3-df7310e3c8e9.png">

**Comment by pipiche38** [comment]
Same here
<img width="870" alt="Screenshot 2021-09-28 at 11 03 45" src="https://user-images.githubusercontent.com/8291674/135057543-ef74b1e1-efba-4c7f-946c-a15becf65c7a.png">

**Comment by fairecasoimeme** [comment]
It depend on EDF subscription and mono/triphasé

IMAX = mono
IMAX1,2,3 = triphasé

IMAX and IMAX1 can't be in the same time

the same for IINST and IINST1

HCHP is a different subscription of EJPHN and BBRHCJB.
This can't be in the same time
