### ISSUE TITLE
0x0702/0x0112 is documented as RP while when seting a Report Config on it we got an error

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#91]
<img width="425" alt="Screenshot 2022-09-12 at 11 29 14" src="https://user-images.githubusercontent.com/8291674/189620379-bb0b2f05-a947-4199-a2d5-68d2f9095839.png">

<img width="421" alt="Screenshot 2022-09-12 at 11 29 05" src="https://user-images.githubusercontent.com/8291674/189620412-27af43d4-3326-4a9e-8d16-c0782700fde5.png">

**Comment by fairecasoimeme** [comment]
I confirm that cluster 0x702 / 0x112 is in RP mode. 
your trace is about read reporting config (0x122 command) not a setting of a report config (0x120 command)
This kind of error could arrive when setting a config report is not passed.
