### ISSUE TITLE
0x0702/0x0110 is documented as RP how when Report Config we got an error

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#92]
<img width="415" alt="Screenshot 2022-09-12 at 11 31 11" src="https://user-images.githubusercontent.com/8291674/189620727-acfc3426-6f5e-4015-aa67-3fad397c3dfd.png">

<img width="420" alt="Screenshot 2022-09-12 at 11 31 18" src="https://user-images.githubusercontent.com/8291674/189620763-d641200c-ca90-4e8e-a3ed-a20c7fcb0875.png">

**Comment by fairecasoimeme** [comment]
I confirm that cluster 0x702 / 0x110 is in RP mode. 
your trace is about read reporting config (0x122 command) not a setting of a report config (0x120 command)
This kind of error could arrive when setting a config report is not passed.

**Comment by pipiche38** [comment]
Juste after a fresh reset of the ZLinky
<img width="510" alt="Screenshot 2022-09-12 at 18 16 27" src="https://user-images.githubusercontent.com/8291674/189704745-63576ca4-b4ed-4ee5-98f0-1ec138e4123e.png">

**Comment by pipiche38** [comment]
<img width="430" alt="Screenshot 2022-09-12 at 18 17 46" src="https://user-images.githubusercontent.com/8291674/189704971-3a144793-000b-4ccf-a7af-e87d71a9eba5.png">

<img width="428" alt="Screenshot 2022-09-12 at 18 17 51" src="https://user-images.githubusercontent.com/8291674/189705009-15455d28-a936-47ec-9714-e416d0110316.png">

**Comment by fairecasoimeme** [comment]
After a reset or a flash erase ?

**Comment by pipiche38** [comment]
A reset

**Comment by fairecasoimeme** [comment]
No a reset is a reboot with a clear of RAM memory and registry . If you want to clear cfg binding table, pairing and other flash memory, it's a factory reset. So what did you do ?
