### ISSUE TITLE
Reporting Configuration of 0x0b04/0x050b.... result in Software Failure !

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#93]
<img width="415" alt="Screenshot 2022-09-12 at 11 32 54" src="https://user-images.githubusercontent.com/8291674/189621204-eab53b5f-22fe-495b-b30d-10e5609ba79b.png">
<img width="425" alt="Screenshot 2022-09-12 at 11 33 02" src="https://user-images.githubusercontent.com/8291674/189621233-94f10416-87c6-4307-a2be-cf32e3640f2d.png">
<img width="423" alt="Screenshot 2022-09-12 at 11 33 17" src="https://user-images.githubusercontent.com/8291674/189621260-c7d4e2a0-8be2-4c41-8714-6ae508dd5bf4.png">
<img width="420" alt="Screenshot 2022-09-12 at 11 33 22" src="https://user-images.githubusercontent.com/8291674/189621294-a9dcf9e3-4100-483b-908f-22badba5f859.png">
<img width="429" alt="Screenshot 2022-09-12 at 11 33 33" src="https://user-images.githubusercontent.com/8291674/189621328-089e8274-f885-46cd-9150-0424f5cc6842.png">
<img width="423" alt="Screenshot 2022-09-12 at 11 33 40" src="https://user-images.githubusercontent.com/8291674/189621357-a335fbf4-e84d-422b-a215-0e5d9f229d5f.png">

**Comment by fairecasoimeme** [comment]
This error message can occur if the config report table is full.
You can verify with a usb-ttl module connected to 115200 baud. when you use the reset button, the device reboot with the config report table

**Comment by pipiche38** [comment]
How can Config Report table be full just after a RESET ? How can we clean it ?

- The ZLinky has been reset

        "ConfigureReporting": {
                "0702": {
                        "Attributes": {
                                "0100": { "DataType": "25", "MinInterval": "0046", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "000000000005" },
                                "0102": { "DataType": "25", "MinInterval": "0046", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "000000000005" },
                                "0104": { "DataType": "25", "MinInterval": "0046", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "000000000005" },
                                "0106": { "DataType": "25", "MinInterval": "0046", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "000000000005" },
                                "0108": { "DataType": "25", "MinInterval": "0046", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "000000000005" },
                                "010a": { "DataType": "25", "MinInterval": "0046", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "000000000005" },
                                "010c": { "DataType": "25", "MinInterval": "0046", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "000000000005" },
                                "010e": { "DataType": "25", "MinInterval": "0046", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "000000000005" },
                                "0110": { "DataType": "25", "MinInterval": "0046", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "000000000005" },
                                "0112": { "DataType": "25", "MinInterval": "0046", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "000000000005" }
                        }
                },
                "0b04": {
                        "Attributes": {
                                "0508": { "DataType": "21", "MinInterval": "000A", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "0001" },
                                "050b": { "DataType": "29", "MinInterval": "000A", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "0001" },
                                "050d": { "DataType": "29", "MinInterval": "000A", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "0001" },
                                "050f": { "DataType": "21", "MinInterval": "000A", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "0001" },
                                "090b": { "DataType": "29", "MinInterval": "000A", "MaxInterval": "0E10", "TimeOut": "0000", "Change": "0001" }
                        }
                },
                "ff66": {
                        "Attributes": {
                                "0203": { "DataType": "23", "MinInterval": "000A", "MaxInterval": "fffe", "TimeOut": "0000", "Change": "00000001" },
                                "0204": { "DataType": "23", "MinInterval": "000A", "MaxInterval": "fffe", "TimeOut": "0000", "Change": "00000001" },
                                "0205": { "DataType": "23", "MinInterval": "000A", "MaxInterval": "fffe", "TimeOut": "0000", "Change": "00000001" },
                                "0206": { "DataType": "23", "MinInterval": "000A", "MaxInterval": "fffe", "TimeOut": "0000", "Change": "00000001" },
                                "0210": { "DataType": "29", "MinInterval": "000A", "MaxInterval": "fffe", "TimeOut": "0000", "Change": "0001" }
                        }
                }
        },

**Comment by fairecasoimeme** [comment]
Please share your debug console to see the config report table.

To clear all the table you have to do a factory reset --> press 10 sec to the link button.
