### ISSUE TITLE
42 kWh ?!

### ISSUE THREAD

**Issue by warlordattack** [fairecasoimeme/Zlinky_TIC#94]
Dans le tableau de bord energie j'ai un chiffre étonnant : 
visiblement je consomme 42 kWh ?!

Sauf erreur j'ai mis la conso BASE du ZLinky_TIC  dans le setup du tableau de bord.
Est-ce un bug ? ou une erreur de ma part ?
A qui je dois le remonter ?

![2022-09-12_110249](https://user-images.githubusercontent.com/3226486/189614954-c18a9bea-5b9c-4062-aa03-f8739add7a69.png)

ici on voit que le chiffre est  3 fois superieur par rapport à avant :
![2022-09-12_114219](https://user-images.githubusercontent.com/3226486/189622906-562f3ec6-d1a8-44b1-a4b1-eebb7ee276ca.png)

Merci de vos lumiéres

**Comment by fairecasoimeme** [comment]
Je pense que c'est parce qu'il y a eu un trou. Du coup, il y a un rattrape qui explique cette consommation (correspondant à x jours).
