### ISSUE TITLE
Bind response: Table full !

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#95]
ZLinky has been reseted as it has moved from Historic mode to Standard mode .
But still issues are poping up

<img width="700" alt="Screenshot 2022-09-12 at 17 27 02" src="https://user-images.githubusercontent.com/8291674/189693995-4e85a1d8-f076-428c-a1e7-908187cbd0e4.png">

<img width="679" alt="Screenshot 2022-09-12 at 17 27 15" src="https://user-images.githubusercontent.com/8291674/189694031-d7c7d142-1285-4ba4-9672-a27450c3bb83.png">

**Comment by fairecasoimeme** [comment]
The bind table is limited to 4 : for cluster : 0x0702 / 0x0b04 / 0xff66 
If the bind table is full, you have to unbind one which is not in the list. this is not an issue
