### ISSUE TITLE
Typo in the mqtt payload

### ISSUE THREAD

**Issue by bdherouville** [fairecasoimeme/Zlinky_TIC#97]
Bonjour,

dans zigbee2mqtt je pense qu'il y a une erreur : active_enerfy_out_d01 ...

n'est-ce pas plutôt energy avec un g ?

Info 2022-09-14 23:40:25MQTT publish: topic 'zigbee2mqtt/ZLinky_TIC', payload '{"active_enerfy_out_d01":null,

**Comment by fairecasoimeme** [comment]
Bonjour,
C'est pas le bon endroit pour ce genre de problème. C'est plutôt côté zigbee2mqtt.
Tu peux peu-être voir avec @vk496

**Comment by bdherouville** [comment]
Bonjour,

désolé. Pour info le ZLinky_TIC fonctionne à merveille. Avec une antenne déportés à 10m via une rallonge.

Cordialement,
