### ISSUE TITLE
why is there differences between router and non router configuration outside of the simple no-route 

### ISSUE THREAD

**Issue by pipiche38** [fairecasoimeme/Zlinky_TIC#99]
exemples like : 

| PARAMETER | NO-ROUTE | ROUTER |
| ------------ | ------------ | -------- |
| MaximumIncomingTransferSize | "200" | 100 |
| MaximumOutgoingTransferSize | "200" | 100 |
| "ZLinky->apduZDP" | 200 | 100 |
| "ZLinky->apduZCL" | 200 | 100 |

This makes one version capable of doing larger chunk of attributes rather the other, and not documented in the release notes

**Comment by fairecasoimeme** [comment]
Hello,
There is a mistake with the router zpscfg file. The 200 values is mandatory to manage https://github.com/fairecasoimeme/Zlinky_TIC/issues/82#issuecomment-1232018371
PJOURF+1 is too long (with header) for APDU.

**Comment by fairecasoimeme** [comment]
Yes, i have to verify other things and do tests and after I publish a pre-release.

**Comment by pdecat** [comment]
Router v8 works fine for me.
